// ============================================================
// 100개 비자 진단 페이지 디자인 기획서 / 100 Visa Diagnosis Page Design Specs
// 기획: Claude (메인 에이전트) / Planned by Claude (Main Agent)
// 디자인: 1~50 Gemini, 51~100 Frontend Designer
// ============================================================

export interface DiagnosisDesignSpec {
  id: number;
  name: string;
  nameEn: string;
  concept: string;          // 큰 틀 컨셉 / High-level concept
  references: string[];     // 4~5개 SaaS 레퍼런스 / 4-5 SaaS references
  inputStyle: string;       // 입력 방식 / Input method style
  resultStyle: string;      // 결과 표시 방식 / Result display style
  keyFeatures: string[];    // 핵심 UI 요소 / Key UI elements
  colorTheme: string;       // 컬러 테마 / Color theme
}

export const diagnosisDesignSpecs: DiagnosisDesignSpec[] = [
  // ============================================================
  // 1~10: 대화형/챗봇 계열 / Conversational & Chatbot
  // ============================================================
  { id: 1, name: '친구처럼 대화', nameEn: 'Friendly Chat', concept: 'AI 챗봇이 친구처럼 질문하며 정보를 수집, 비자 경로를 추천', references: ['ChatGPT', 'Intercom', 'Drift', 'Typeform', 'WhatsApp'], inputStyle: '채팅 말풍선으로 한 질문씩', resultStyle: '챗봇이 카드형 결과를 메시지로 전송', keyFeatures: ['타이핑 애니메이션', '말풍선 UI', '이모지 리액션', '빠른 답변 칩'], colorTheme: '화이트+블루 그라데이션' },
  { id: 2, name: '음성 인터뷰', nameEn: 'Voice Interview', concept: '마이크 아이콘과 음파 시각화로 음성 인터뷰 느낌의 입력 UI', references: ['Siri', 'Google Assistant', 'Otter.ai', 'Rev', 'Whisper'], inputStyle: '음파 애니메이션 + 텍스트 입력 병행', resultStyle: '트랜스크립트 형태로 결과 표시', keyFeatures: ['음파 시각화', '녹음 버튼 UI', '실시간 텍스트 변환', 'STT 인디케이터'], colorTheme: '다크 모드+네온 퍼플' },
  { id: 3, name: 'AI 상담사', nameEn: 'AI Counselor', concept: '전문 이민 상담사 아바타가 단계별로 질문하는 컨설팅 UI', references: ['Calendly', 'Loom', 'Zoom', 'HubSpot', 'Zendesk'], inputStyle: '상담사 프로필 + 채팅 형식', resultStyle: '상담 리포트 PDF 스타일', keyFeatures: ['상담사 아바타', '비디오 프레임 UI', '상담 타임라인', '리포트 다운로드'], colorTheme: '네이비+골드' },
  { id: 4, name: '스토리 대화', nameEn: 'Story Dialogue', concept: '인스타그램 스토리처럼 탭하며 진행하는 대화형 진단', references: ['Instagram Stories', 'Snapchat', 'TikTok', 'BeReal', 'Threads'], inputStyle: '스토리 탭 + 스와이프 답변', resultStyle: '스토리 하이라이트로 결과 저장', keyFeatures: ['프로그레스 바', '전체 화면', '탭 네비게이션', '스와이프 제스처'], colorTheme: '그라데이션 핑크~퍼플' },
  { id: 5, name: '메신저 봇', nameEn: 'Messenger Bot', concept: '카카오톡/라인 메신저 봇처럼 버튼으로 선택하며 진행', references: ['KakaoTalk', 'LINE', 'Telegram', 'WeChat', 'Facebook Messenger'], inputStyle: '말풍선 + 하단 버튼 그리드', resultStyle: '카카오 카드 메시지 형태', keyFeatures: ['노란 말풍선', '버튼 메뉴', '캐러셀 카드', '공유하기 버튼'], colorTheme: '카카오 옐로우+화이트' },
  { id: 6, name: '터미널 CLI', nameEn: 'Terminal CLI', concept: '개발자 터미널처럼 명령어로 진단하는 해커 스타일', references: ['Vercel', 'GitHub Copilot', 'Warp', 'iTerm2', 'Railway'], inputStyle: '커맨드 라인 입력 + 자동완성', resultStyle: 'JSON/테이블 형태 출력', keyFeatures: ['모노스페이스 폰트', '커서 깜빡임', '자동완성', '구문 하이라이팅'], colorTheme: '다크+그린 모노크롬' },
  { id: 7, name: 'SMS 문자', nameEn: 'SMS Thread', concept: 'iMessage 스타일 문자 대화로 간편하게 진단', references: ['iMessage', 'Google Messages', 'Signal', 'Discord', 'Slack'], inputStyle: 'SMS 버블 + 빠른 답변', resultStyle: 'MMS 카드 형태', keyFeatures: ['블루/그린 버블', '읽음 표시', '타이핑 인디케이터', '리치 링크 프리뷰'], colorTheme: 'iOS 블루+화이트' },
  { id: 8, name: '이메일 스레드', nameEn: 'Email Thread', concept: '이메일 왕복 형식으로 정보를 주고받는 비즈니스 스타일', references: ['Gmail', 'Outlook', 'Superhuman', 'Front', 'Spark'], inputStyle: '이메일 작성 폼 + 인라인 답변', resultStyle: '이메일 뉴스레터 형태', keyFeatures: ['To/From 헤더', '인라인 답변', '첨부파일 스타일', '폴더 정리'], colorTheme: '화이트+레드 액센트' },
  { id: 9, name: 'RPG 대화', nameEn: 'RPG Dialogue', concept: 'RPG 게임의 NPC 대화창처럼 선택지를 고르며 진단', references: ['Genshin Impact', 'Final Fantasy', 'Persona', 'Baldurs Gate', 'Undertale'], inputStyle: '대화창 + 선택지 분기', resultStyle: '퀘스트 완료 화면', keyFeatures: ['캐릭터 일러스트', '대화창 프레임', '선택지 분기', '경험치 바'], colorTheme: '다크 판타지+골드' },
  { id: 10, name: '인터뷰 영상', nameEn: 'Video Interview', concept: '영상 면접처럼 질문이 영상 형식으로 나오는 UI', references: ['HireVue', 'Zoom', 'Loom', 'Riverside', 'StreamYard'], inputStyle: '영상 프레임 + 하단 답변 버튼', resultStyle: '면접 피드백 카드', keyFeatures: ['비디오 플레이어 UI', '타임스탬프', '녹화 표시', '피드백 패널'], colorTheme: '블랙+블루 프로페셔널' },

  // ============================================================
  // 11~20: 폼/위자드 계열 / Form & Wizard
  // ============================================================
  { id: 11, name: '원페이지 폼', nameEn: 'One-Page Form', concept: '모든 입력을 하나의 깔끔한 페이지에서 완료', references: ['Stripe', 'Linear', 'Notion', 'Supabase', 'Vercel'], inputStyle: '섹션별 스크롤 폼', resultStyle: '인라인 결과 패널', keyFeatures: ['플로팅 레이블', '실시간 유효성', '프로그레스 인디케이터', '스무스 스크롤'], colorTheme: '미니멀 화이트+인디고' },
  { id: 12, name: '카드 위자드', nameEn: 'Card Wizard', concept: '카드를 넘기듯 단계별로 진행하는 마법사 UI', references: ['Airbnb', 'Booking.com', 'Kayak', 'Expedia', 'TripAdvisor'], inputStyle: '카드 슬라이드 + 좌우 네비게이션', resultStyle: '여행 일정표 스타일 결과', keyFeatures: ['카드 전환 애니메이션', '브레드크럼', '뒤로가기', '프리뷰 사이드바'], colorTheme: '코랄+웜 화이트' },
  { id: 13, name: '타임라인 폼', nameEn: 'Timeline Form', concept: '세로 타임라인을 따라 내려가며 정보를 입력', references: ['Asana', 'Monday.com', 'ClickUp', 'Jira', 'Trello'], inputStyle: '타임라인 노드별 입력', resultStyle: '완성된 타임라인 + 결과 카드', keyFeatures: ['세로 타임라인', '노드 애니메이션', '진행 바', '완료 체크마크'], colorTheme: '화이트+그린 프로그레스' },
  { id: 14, name: '슬라이더 폼', nameEn: 'Slider Form', concept: '모든 입력을 슬라이더와 토글로만 구성한 인터랙티브 폼', references: ['Spotify', 'SoundCloud', 'Ableton', 'Figma', 'Framer'], inputStyle: '레인지 슬라이더 + 토글 스위치', resultStyle: '이퀄라이저 스타일 결과 차트', keyFeatures: ['커스텀 슬라이더', '실시간 프리뷰', '토글 스위치', '드래그 인터랙션'], colorTheme: '다크+스포티파이 그린' },
  { id: 15, name: '모바일 퍼스트 스텝', nameEn: 'Mobile-First Steps', concept: '모바일에 최적화된 한 화면에 한 질문씩', references: ['Toss', 'Revolut', 'Monzo', 'Cash App', 'Venmo'], inputStyle: '풀스크린 한 질문 + 큰 버튼', resultStyle: '금융 리포트 스타일', keyFeatures: ['큰 타이포그래피', '하단 CTA', '숫자 키패드', '스와이프 진행'], colorTheme: '토스 블루+화이트' },
  { id: 16, name: '설문조사', nameEn: 'Survey Style', concept: 'Google Forms/SurveyMonkey 스타일의 설문조사 형식', references: ['Typeform', 'Google Forms', 'SurveyMonkey', 'Tally', 'Jotform'], inputStyle: '한 질문씩 전체 화면', resultStyle: '설문 결과 통계 차트', keyFeatures: ['번호 매김', '키보드 숏컷', '진행률 %', '감사 화면'], colorTheme: '화이트+타입폼 블루' },
  { id: 17, name: '체크리스트', nameEn: 'Checklist', concept: 'To-do 체크리스트처럼 조건을 하나씩 체크하며 진행', references: ['Todoist', 'Things 3', 'TickTick', 'Any.do', 'Notion'], inputStyle: '체크박스 리스트 + 섹션 접기', resultStyle: '완료/미완료 체크리스트 결과', keyFeatures: ['체크 애니메이션', '섹션 아코디언', '완료율 표시', '우선순위 태그'], colorTheme: '레드 액센트+화이트' },
  { id: 18, name: '마인드맵 입력', nameEn: 'Mind Map Input', concept: '마인드맵처럼 중심에서 가지를 뻗으며 정보 입력', references: ['Miro', 'FigJam', 'Whimsical', 'MindMeister', 'Excalidraw'], inputStyle: '노드 연결 + 드래그 배치', resultStyle: '완성된 마인드맵 결과', keyFeatures: ['캔버스 UI', '줌/팬', '노드 연결선', '자동 레이아웃'], colorTheme: '화이트 캔버스+컬러풀 노드' },
  { id: 19, name: '캘린더 기반', nameEn: 'Calendar Based', concept: '입국 날짜부터 역산하며 일정을 잡는 캘린더 중심 UI', references: ['Google Calendar', 'Calendly', 'Cal.com', 'Fantastical', 'Cron'], inputStyle: '날짜 선택 + 이벤트 등록', resultStyle: '비자 일정 캘린더 뷰', keyFeatures: ['달력 위젯', '드래그 일정', '알림 설정', '타임존 표시'], colorTheme: '화이트+구글 블루' },
  { id: 20, name: '프로필 빌더', nameEn: 'Profile Builder', concept: 'LinkedIn 프로필 완성하듯 빈 필드를 채워가는 UI', references: ['LinkedIn', 'Behance', 'Dribbble', 'GitHub', 'Portfolio.dev'], inputStyle: '프로필 카드 빈칸 채우기', resultStyle: '완성된 비자 프로필 카드', keyFeatures: ['완성도 게이지', '프로필 카드 프리뷰', '추천 배지', '소셜 스타일'], colorTheme: 'LinkedIn 블루+화이트' },

  // ============================================================
  // 21~30: 게임/인터랙티브 계열 / Gamified & Interactive
  // ============================================================
  { id: 21, name: '퀴즈쇼', nameEn: 'Quiz Show', concept: '퀴즈쇼 형식으로 재미있게 정보를 입력받는 UI', references: ['Kahoot', 'Quizlet', 'Duolingo', 'Trivia Crack', 'HQ Trivia'], inputStyle: '4지선다 퀴즈 + 타이머', resultStyle: '퀴즈 결과 점수판', keyFeatures: ['카운트다운 타이머', '정답 애니메이션', '점수 시스템', '리더보드'], colorTheme: '퍼플+옐로우 비비드' },
  { id: 22, name: 'RPG 캐릭터 생성', nameEn: 'RPG Character Creation', concept: 'RPG 캐릭터 생성처럼 능력치를 배분하는 진단 UI', references: ['Diablo', 'World of Warcraft', 'Lost Ark', 'Path of Exile', 'DnD Beyond'], inputStyle: '능력치 포인트 배분 + 클래스 선택', resultStyle: '캐릭터 시트 + 스킬 트리', keyFeatures: ['스탯 바', '클래스 아이콘', '레벨업 효과', '장비 슬롯'], colorTheme: '다크 판타지+오렌지' },
  { id: 23, name: '보드게임', nameEn: 'Board Game', concept: '보드게임 판을 따라가며 칸칸이 정보를 입력', references: ['Monopoly GO', 'Catan', 'Ludo King', 'BoardGameArena', 'Tabletopia'], inputStyle: '주사위 굴리기 + 칸 이동', resultStyle: '완주 보상 화면', keyFeatures: ['게임 보드 맵', '주사위 애니메이션', '미니어처 토큰', '이벤트 카드'], colorTheme: '파스텔 그린+우드 텍스처' },
  { id: 24, name: '타로 카드', nameEn: 'Tarot Card', concept: '타로 카드를 뒤집으며 운명적으로 비자 경로를 발견', references: ['Co-Star', 'The Pattern', 'Sanctuary', 'Astrology Zone', 'Mystic Mondays'], inputStyle: '카드 뒤집기 + 선택', resultStyle: '타로 리딩 결과 페이지', keyFeatures: ['카드 플립 3D', '신비로운 일러스트', '별자리 배경', '리딩 해석'], colorTheme: '다크 네이비+골드 스타' },
  { id: 25, name: '미로 탈출', nameEn: 'Maze Runner', concept: '미로를 탐색하며 분기점에서 선택하는 어드벤처 진단', references: ['Monument Valley', 'Alto Adventure', 'Journey', 'Sky', 'Gris'], inputStyle: '미로 경로 선택 + 방향키', resultStyle: '탈출 경로 = 비자 경로', keyFeatures: ['미로 맵 UI', '캐릭터 이동', '분기점 선택', '보물 발견'], colorTheme: '미니멀 파스텔+골드' },
  { id: 26, name: '슬롯머신', nameEn: 'Slot Machine', concept: '슬롯머신 릴을 돌려 조건을 매칭하는 즐거운 진단', references: ['Coinbase', 'Robinhood', 'eToro', 'Binance', 'Crypto.com'], inputStyle: '릴 스핀 + 옵션 정지', resultStyle: '잭팟 결과 화면', keyFeatures: ['릴 애니메이션', '매칭 효과', '코인 애니메이션', '보너스 라운드'], colorTheme: '골드+레드 럭키' },
  { id: 27, name: '퍼즐 맞추기', nameEn: 'Puzzle Piece', concept: '퍼즐 조각을 맞추듯 조건들을 조합하여 완성하는 UI', references: ['Canva', 'Adobe Express', 'PicsArt', 'Figma', 'Sketch'], inputStyle: '드래그 앤 드롭 퍼즐', resultStyle: '완성된 퍼즐 = 비자 로드맵', keyFeatures: ['드래그 앤 드롭', '스냅 효과', '완성 애니메이션', '힌트 시스템'], colorTheme: '화이트+멀티컬러 조각' },
  { id: 28, name: '레이싱 트랙', nameEn: 'Racing Track', concept: '레이싱 트랙을 달리며 체크포인트에서 정보를 입력', references: ['F1 TV', 'Mario Kart', 'Gran Turismo', 'Need for Speed', 'Forza'], inputStyle: '트랙 진행 + 체크포인트 입력', resultStyle: '레이스 결과 + 랩타임', keyFeatures: ['트랙 맵', '속도 게이지', '체크포인트 깃발', '순위표'], colorTheme: '블랙+레드 레이싱' },
  { id: 29, name: '탐험 지도', nameEn: 'Explorer Map', concept: '보물 지도를 따라가며 숨겨진 비자 경로를 발견', references: ['Google Maps', 'Mapbox', 'Apple Maps', 'What3Words', 'Strava'], inputStyle: '지도 핀 찍기 + 경로 선택', resultStyle: '탐험 완료 지도 + 보물(결과)', keyFeatures: ['인터랙티브 맵', '핀 애니메이션', '경로 드로잉', '미니맵'], colorTheme: '빈티지 세피아+네이비' },
  { id: 30, name: '우주 탐사', nameEn: 'Space Explorer', concept: '우주선을 조종하며 행성(단계)을 방문하는 SF 진단', references: ['SpaceX', 'NASA', 'Star Citizen', 'No Mans Sky', 'Kerbal Space'], inputStyle: '행성 선택 + 우주선 이동', resultStyle: '탐사 보고서 + 항성 경로', keyFeatures: ['별 배경 파티클', '행성 오빗', '우주선 애니메이션', '궤도 라인'], colorTheme: '다크 스페이스+네온 시안' },

  // ============================================================
  // 31~40: 대시보드/분석 계열 / Dashboard & Analytics
  // ============================================================
  { id: 31, name: '금융 대시보드', nameEn: 'Finance Dashboard', concept: '투자 앱처럼 포트폴리오 분석하듯 비자 경로를 분석', references: ['Bloomberg Terminal', 'TradingView', 'Yahoo Finance', 'Robinhood', 'Wealthfront'], inputStyle: '사이드바 필터 + 실시간 업데이트', resultStyle: '차트+테이블 대시보드', keyFeatures: ['캔들스틱 차트', '실시간 티커', '포트폴리오 파이', '뉴스 피드'], colorTheme: '다크+그린 트레이딩' },
  { id: 32, name: '건강 진단서', nameEn: 'Health Report', concept: '건강검진 결과서처럼 각 항목을 체계적으로 분석', references: ['Apple Health', 'Fitbit', 'Samsung Health', 'Oura Ring', 'Whoop'], inputStyle: '건강 검진 문진표 스타일', resultStyle: '건강 리포트 카드 + 수치 그래프', keyFeatures: ['바이탈 사인 링', '정상/주의/위험 컬러', '트렌드 그래프', '종합 점수'], colorTheme: '화이트+애플 헬스 그라데이션' },
  { id: 33, name: 'CRM 파이프라인', nameEn: 'CRM Pipeline', concept: '세일즈 파이프라인처럼 비자 진행 단계를 칸반으로 표시', references: ['Salesforce', 'HubSpot', 'Pipedrive', 'Close', 'Copper'], inputStyle: '칸반 보드 + 드래그 카드', resultStyle: '파이프라인 뷰 + 전환율', keyFeatures: ['칸반 컬럼', '드래그 앤 드롭', '딜 금액 합계', '전환 퍼널'], colorTheme: '화이트+세일즈포스 블루' },
  { id: 34, name: '코드 에디터', nameEn: 'Code Editor', concept: 'VS Code처럼 코드를 작성하듯 비자 조건을 입력', references: ['VS Code', 'GitHub', 'GitLab', 'Replit', 'CodeSandbox'], inputStyle: 'JSON/YAML 형식 에디터', resultStyle: '빌드 결과 터미널 + 성공/실패', keyFeatures: ['구문 하이라이팅', '자동 완성', '에러 밑줄', '미니맵'], colorTheme: '다크 모드+VS Code 블루' },
  { id: 35, name: '프로젝트 관리', nameEn: 'Project Manager', concept: '프로젝트 관리 도구처럼 비자를 프로젝트로 관리', references: ['Asana', 'Notion', 'Linear', 'Height', 'Shortcut'], inputStyle: '이슈 생성 폼 + 라벨/우선순위', resultStyle: '프로젝트 보드 + 간트 차트', keyFeatures: ['이슈 카드', '간트 차트', '스프린트 보드', '라벨 시스템'], colorTheme: '화이트+리니어 퍼플' },
  { id: 36, name: 'CI/CD 파이프라인', nameEn: 'CI/CD Pipeline', concept: '배포 파이프라인처럼 비자 단계를 빌드/테스트/배포로 표현', references: ['GitHub Actions', 'CircleCI', 'Jenkins', 'Vercel', 'Netlify'], inputStyle: '파이프라인 노드 설정', resultStyle: '빌드 성공/실패 로그', keyFeatures: ['파이프라인 그래프', '빌드 로그', '성공/실패 배지', '환경변수'], colorTheme: '다크+GitHub 그린' },
  { id: 37, name: '데이터 시각화', nameEn: 'Data Visualization', concept: '복잡한 데이터를 아름다운 차트로 시각화하는 분석 UI', references: ['Tableau', 'Power BI', 'Looker', 'Metabase', 'Grafana'], inputStyle: '필터 패널 + 차트 인터랙션', resultStyle: '대시보드 + 드릴다운 차트', keyFeatures: ['산키 다이어그램', '레이더 차트', '히트맵', '버블 차트'], colorTheme: '다크+데이터 비비드' },
  { id: 38, name: '신용 점수', nameEn: 'Credit Score', concept: '신용 점수 조회처럼 비자 적합도 점수를 원형 게이지로 표시', references: ['Credit Karma', 'FICO', 'NerdWallet', 'Mint', 'Personal Capital'], inputStyle: '간단한 정보 입력 폼', resultStyle: '크레딧 스코어 게이지 + 팩터 분석', keyFeatures: ['원형 스코어 게이지', '등급 컬러', '팩터 바', '트렌드 그래프'], colorTheme: '그린 그라데이션+화이트' },
  { id: 39, name: '과학 실험실', nameEn: 'Science Lab', concept: '실험실에서 실험하듯 변수를 조합하여 결과를 도출', references: ['Wolfram Alpha', 'Desmos', 'Khan Academy', 'Brilliant', 'Coursera'], inputStyle: '변수 조절 패널 + 실시간 시뮬레이션', resultStyle: '실험 결과 보고서 + 그래프', keyFeatures: ['변수 슬라이더', '실시간 그래프', '수식 표시', '실험 로그'], colorTheme: '화이트+블루 사이언스' },
  { id: 40, name: '날씨 예보', nameEn: 'Weather Forecast', concept: '날씨 예보 앱처럼 비자 경로의 전망을 표시', references: ['Apple Weather', 'AccuWeather', 'Weather.com', 'Dark Sky', 'Windy'], inputStyle: '위치/조건 설정', resultStyle: '날씨 카드 + 주간 예보 스타일', keyFeatures: ['날씨 아이콘 매핑', '온도 그래프→점수', '주간 예보 바', '레이더 맵'], colorTheme: '스카이 블루 그라데이션' },

  // ============================================================
  // 41~50: 여행/탐색 계열 / Travel & Exploration
  // ============================================================
  { id: 41, name: '항공편 검색', nameEn: 'Flight Search', concept: '항공편 예약하듯 출발지(현재)→도착지(목표)를 검색', references: ['Google Flights', 'Skyscanner', 'Hopper', 'Kiwi.com', 'Momondo'], inputStyle: '출발/도착 선택 + 날짜 + 필터', resultStyle: '항공편 목록 + 가격 비교', keyFeatures: ['출발→도착 UI', '가격 캘린더', '필터 사이드바', '정렬 옵션'], colorTheme: '화이트+스카이 블루' },
  { id: 42, name: '여행 일정표', nameEn: 'Travel Itinerary', concept: '여행 일정 앱처럼 비자 경로를 여행 코스로 표현', references: ['TripIt', 'Wanderlog', 'Google Travel', 'Roadtrippers', 'Rome2Rio'], inputStyle: '일정 추가 + 드래그 정렬', resultStyle: '여행 일정 타임라인', keyFeatures: ['일정 카드', '지도 연동', '시간 블록', '메모 첨부'], colorTheme: '오렌지+화이트 여행' },
  { id: 43, name: '호텔 예약', nameEn: 'Hotel Booking', concept: '호텔 예약처럼 비자 유형을 객실처럼 비교 선택', references: ['Airbnb', 'Booking.com', 'Hotels.com', 'Agoda', 'Trivago'], inputStyle: '체크인/아웃 + 필터 + 지도', resultStyle: '호텔 카드 목록 + 비교', keyFeatures: ['이미지 캐러셀', '별점', '가격 필터', '지도 핀'], colorTheme: 'Airbnb 코랄+화이트' },
  { id: 44, name: '지하철 노선도', nameEn: 'Subway Map', concept: '지하철 노선도처럼 비자 경로를 노선으로 시각화', references: ['Citymapper', 'Google Maps Transit', 'Moovit', 'Transit', 'KakaoMap'], inputStyle: '출발역→도착역 선택', resultStyle: '노선도 경로 + 환승 정보', keyFeatures: ['SVG 노선도', '역 노드', '환승 표시', '소요시간 계산'], colorTheme: '화이트+멀티컬러 노선' },
  { id: 45, name: 'GPS 내비', nameEn: 'GPS Navigation', concept: '내비게이션처럼 현재 위치에서 목표까지 경로 안내', references: ['Waze', 'Google Maps', 'TomTom', 'HERE', 'Sygic'], inputStyle: '출발/도착 + 경로 옵션', resultStyle: '턴바이턴 경로 안내', keyFeatures: ['맵 뷰', '경로 하이라이트', 'ETA 표시', '대안 경로'], colorTheme: '다크 맵+블루 경로' },
  { id: 46, name: '배낭여행', nameEn: 'Backpacker', concept: '배낭여행자 스타일로 자유롭게 경로를 탐색', references: ['Hostelworld', 'Couchsurfing', 'Workaway', 'WWOOF', 'Nomadlist'], inputStyle: '자유 텍스트 + 태그 선택', resultStyle: '배낭여행 루트 맵', keyFeatures: ['핀 마커', '여행 노트', '예산 계산기', '커뮤니티 리뷰'], colorTheme: '어스 톤+그린' },
  { id: 47, name: '크루즈 항해', nameEn: 'Cruise Voyage', concept: '크루즈 여행처럼 기항지(단계)를 순서대로 방문', references: ['Royal Caribbean', 'Viking', 'Celebrity Cruises', 'MSC', 'Princess'], inputStyle: '기항지 선택 + 일정 설정', resultStyle: '항해 루트 맵 + 기항지 카드', keyFeatures: ['바다 배경', '선박 애니메이션', '기항지 카드', '일정표'], colorTheme: '오션 블루+화이트' },
  { id: 48, name: '등산 코스', nameEn: 'Hiking Trail', concept: '등산 앱처럼 정상(목표)까지 코스를 선택하며 오르기', references: ['AllTrails', 'Strava', 'Komoot', 'Gaia GPS', 'PeakVisor'], inputStyle: '트레일 선택 + 난이도 필터', resultStyle: '등반 프로필 그래프 + 코스 상세', keyFeatures: ['고도 프로필', '난이도 배지', '체크포인트', '경치 사진'], colorTheme: '그린+어스 브라운' },
  { id: 49, name: '우편 배송', nameEn: 'Package Tracking', concept: '택배 추적처럼 비자 진행 상태를 실시간 추적', references: ['FedEx', 'UPS', 'DHL', 'USPS', 'Coupang'], inputStyle: '배송 정보 입력 (발송인=현재, 수취인=목표)', resultStyle: '배송 추적 타임라인', keyFeatures: ['추적 번호', '단계별 체크', '예상 도착일', '배송 맵'], colorTheme: 'FedEx 퍼플+오렌지' },
  { id: 50, name: '기차 시간표', nameEn: 'Train Timetable', concept: '기차 시간표처럼 출발/도착/환승을 체계적으로 표시', references: ['Deutsche Bahn', 'SNCF', 'Trainline', 'Amtrak', 'KTX 코레일'], inputStyle: '출발역+도착역+시간 선택', resultStyle: '시간표 리스트 + 환승 안내', keyFeatures: ['시간표 그리드', '플랫폼 번호', '환승 시간', '좌석 등급'], colorTheme: 'DB 레드+화이트' },

  // ============================================================
  // 51~60: 교육/학습 계열 / Education & Learning
  // ============================================================
  { id: 51, name: '온라인 수업', nameEn: 'Online Course', concept: '온라인 강의처럼 모듈별로 학습하며 진단 완료', references: ['Udemy', 'Coursera', 'edX', 'Skillshare', 'MasterClass'], inputStyle: '강의 모듈 진행 + 퀴즈', resultStyle: '수료증 + 성적표', keyFeatures: ['비디오 섹션', '진도율 바', '퀴즈 카드', '수료증 디자인'], colorTheme: 'Udemy 퍼플+화이트' },
  { id: 52, name: '플래시카드', nameEn: 'Flashcard', concept: '단어장 플래시카드처럼 뒤집으며 정보를 입력', references: ['Anki', 'Quizlet', 'Brainscape', 'Memrise', 'Duolingo'], inputStyle: '카드 뒤집기 + 옵션 선택', resultStyle: '학습 완료 통계 + 결과 카드덱', keyFeatures: ['3D 카드 플립', '자신감 레벨', '반복 스케줄', '덱 관리'], colorTheme: 'Quizlet 블루+화이트' },
  { id: 53, name: '언어 학습', nameEn: 'Language Learning', concept: '듀오링고처럼 게이미피케이션으로 재미있게 진단', references: ['Duolingo', 'Babbel', 'Rosetta Stone', 'Busuu', 'Lingodeer'], inputStyle: '레슨 단위 + 하트/생명', resultStyle: '레벨업 + 경험치 + 리포트', keyFeatures: ['마스코트 캐릭터', 'XP 바', '스트릭 카운터', '리그 시스템'], colorTheme: '듀오링고 그린+화이트' },
  { id: 54, name: '시험 답안지', nameEn: 'Exam Sheet', concept: 'OMR 답안지처럼 마킹하며 진단하는 시험 스타일', references: ['SAT', 'TOEFL', 'ETS', 'College Board', 'Khan Academy'], inputStyle: 'OMR 버블 마킹 + 시간 제한', resultStyle: '성적표 + 합격/불합격', keyFeatures: ['OMR 마킹 UI', '타이머', '문제 번호 네비', '채점 애니메이션'], colorTheme: '화이트+블랙 시험지' },
  { id: 55, name: '연구 논문', nameEn: 'Research Paper', concept: '학술 논문 형식으로 체계적인 진단 리포트를 제공', references: ['Google Scholar', 'ResearchGate', 'Academia.edu', 'Semantic Scholar', 'arXiv'], inputStyle: '연구 질문 양식 + 방법론 선택', resultStyle: '논문 형식 결과 (초록/본문/결론)', keyFeatures: ['인용 스타일', '차트/표', '참고문헌', 'PDF 스타일'], colorTheme: '아이보리+세리프 블랙' },
  { id: 56, name: '독서 클럽', nameEn: 'Book Club', concept: '전자책 리더처럼 페이지를 넘기며 정보를 읽고 선택', references: ['Kindle', 'Apple Books', 'Audible', 'Goodreads', 'Libby'], inputStyle: '페이지 넘기기 + 밑줄/메모', resultStyle: '책 요약 + 북마크 하이라이트', keyFeatures: ['페이지 넘김 효과', '밑줄 하이라이트', '메모 사이드바', '목차 네비'], colorTheme: '크림+다크 브라운' },
  { id: 57, name: '과학 키트', nameEn: 'Science Kit', concept: '과학 실험 키트처럼 재료를 조합하여 결과를 만들기', references: ['KiwiCo', 'MEL Science', 'Brilliant', 'Exploratorium', 'LEGO Education'], inputStyle: '재료 카드 선택 + 조합', resultStyle: '실험 결과 + 반응 애니메이션', keyFeatures: ['재료 카드', '조합 영역', '반응 시각화', '레시피 카드'], colorTheme: '화이트+사이언스 그린' },
  { id: 58, name: '코딩 튜토리얼', nameEn: 'Coding Tutorial', concept: '코딩 학습처럼 단계별 실습으로 비자 조건을 이해', references: ['freeCodeCamp', 'Codecademy', 'LeetCode', 'HackerRank', 'Exercism'], inputStyle: '코드 편집기 + 실행 버튼', resultStyle: '테스트 통과/실패 + 코드 결과', keyFeatures: ['코드 에디터', '테스트 케이스', '힌트 시스템', '진도 트리'], colorTheme: '다크+fCC 네이비' },
  { id: 59, name: '요리 레시피', nameEn: 'Cooking Recipe', concept: '요리 레시피처럼 재료(조건)와 순서(단계)로 비자를 조리', references: ['Tasty', 'Yummly', 'Allrecipes', 'Cookpad', 'Paprika'], inputStyle: '재료 체크 + 단계별 진행', resultStyle: '완성 요리 = 비자 경로', keyFeatures: ['재료 목록', '단계별 사진', '타이머', '난이도 표시'], colorTheme: '오렌지+크림 푸드' },
  { id: 60, name: '박물관 투어', nameEn: 'Museum Tour', concept: '박물관 오디오 가이드처럼 전시물(비자)을 둘러보며 탐색', references: ['Google Arts', 'MoMA', 'Smartify', 'Cuseum', 'Bloomberg Connects'], inputStyle: '전시실 선택 + 작품 탭', resultStyle: '투어 요약 + 관람 기록', keyFeatures: ['전시실 레이아웃', '오디오 플레이어', '작품 카드', '큐레이션'], colorTheme: '화이트 갤러리+골드' },

  // ============================================================
  // 61~70: 소셜/커뮤니티 계열 / Social & Community
  // ============================================================
  { id: 61, name: 'SNS 피드', nameEn: 'Social Feed', concept: 'SNS 피드처럼 비자 정보를 포스트 형태로 탐색', references: ['Instagram', 'Twitter/X', 'Facebook', 'LinkedIn', 'Threads'], inputStyle: '포스트 작성 + 태그', resultStyle: '피드 타임라인 결과', keyFeatures: ['포스트 카드', '좋아요/댓글', '해시태그', '스토리 링'], colorTheme: '인스타 그라데이션' },
  { id: 62, name: '매칭 앱', nameEn: 'Matching App', concept: '데이팅 앱처럼 비자와 매칭하는 스와이프 UI', references: ['Tinder', 'Bumble', 'Hinge', 'Coffee Meets Bagel', 'OkCupid'], inputStyle: '프로필 작성 + 선호도', resultStyle: '매칭 카드 + 호환도', keyFeatures: ['스와이프 카드', '매칭 애니메이션', '호환도 %', '슈퍼라이크'], colorTheme: '핑크 그라데이션+화이트' },
  { id: 63, name: '레딧 스레드', nameEn: 'Reddit Thread', concept: '레딧 포럼처럼 Q&A 스레드 형식으로 진단', references: ['Reddit', 'Hacker News', 'Stack Overflow', 'Quora', 'Product Hunt'], inputStyle: '질문 포스트 + 댓글 답변', resultStyle: '베스트 답변 = 최적 경로', keyFeatures: ['업보트/다운보트', '스레드 들여쓰기', 'OP 배지', '어워드'], colorTheme: 'Reddit 오렌지+다크' },
  { id: 64, name: '틱톡 릴스', nameEn: 'TikTok Reels', concept: '숏폼 영상 피드처럼 비자 정보를 짧은 카드로 스크롤', references: ['TikTok', 'YouTube Shorts', 'Instagram Reels', 'Snapchat', 'Triller'], inputStyle: '세로 스크롤 + 탭 선택', resultStyle: '릴스 형태 결과 카드', keyFeatures: ['풀스크린 카드', '세로 스크롤', '하트/댓글', '뮤직 바'], colorTheme: '다크+TikTok 시안+핑크' },
  { id: 65, name: '디스코드 서버', nameEn: 'Discord Server', concept: '디스코드 서버 채널처럼 카테고리별로 비자 정보 탐색', references: ['Discord', 'Slack', 'Microsoft Teams', 'Guilded', 'Revolt'], inputStyle: '채널 선택 + 메시지 입력', resultStyle: '서버 대시보드 + 역할 배지', keyFeatures: ['채널 사이드바', '역할 배지', '음성 채널 UI', '핀 메시지'], colorTheme: 'Discord 보라+다크' },
  { id: 66, name: '핀터레스트 보드', nameEn: 'Pinterest Board', concept: '핀터레스트처럼 비자 경로를 보드에 핀으로 저장', references: ['Pinterest', 'Are.na', 'Savee', 'Designspiration', 'Cosmos'], inputStyle: '핀 탐색 + 보드 저장', resultStyle: '비자 보드 + 핀 컬렉션', keyFeatures: ['메이슨리 그리드', '핀 저장', '보드 생성', '추천 핀'], colorTheme: 'Pinterest 레드+화이트' },
  { id: 67, name: '유튜브 학습', nameEn: 'YouTube Academy', concept: '유튜브 강의처럼 비자 가이드 영상 시리즈를 시청', references: ['YouTube', 'Vimeo', 'Nebula', 'CuriosityStream', 'Twitch'], inputStyle: '영상 선택 + 챕터 이동', resultStyle: '시리즈 완료 + 수료증', keyFeatures: ['영상 플레이어', '챕터 마커', '재생목록', '좋아요/구독'], colorTheme: 'YouTube 레드+화이트' },
  { id: 68, name: '클럽하우스 대화', nameEn: 'Clubhouse Room', concept: '오디오 룸에서 전문가와 대화하며 진단하는 느낌', references: ['Clubhouse', 'Twitter Spaces', 'Spotify Greenroom', 'Discord Stage', 'Fireside'], inputStyle: '오디오 룸 UI + 손들기', resultStyle: '대화 요약 + 결론 카드', keyFeatures: ['아바타 서클', '손들기 버튼', '음파 인디케이터', '룸 토픽'], colorTheme: '크림+브라운 엘레강스' },
  { id: 69, name: '네이버 카페', nameEn: 'Naver Cafe', concept: '네이버 카페 게시판 형태로 비자 정보를 게시글로 탐색', references: ['Naver Cafe', 'Daum Cafe', 'DCinside', 'Blind', 'Everytime'], inputStyle: '게시글 작성 + 검색', resultStyle: '인기글 순위 + 댓글 토론', keyFeatures: ['게시판 리스트', '인기글 배지', '댓글 트리', '카페 등급'], colorTheme: '네이버 그린+화이트' },
  { id: 70, name: '위키백과', nameEn: 'Wikipedia', concept: '위키처럼 비자 정보를 백과사전 형태로 체계적 제공', references: ['Wikipedia', 'Notion Wiki', 'Confluence', 'GitBook', 'Docusaurus'], inputStyle: '검색 + 카테고리 탐색', resultStyle: '위키 문서 + 목차 + 관련 항목', keyFeatures: ['목차 사이드바', '인포박스', '내부 링크', '편집 이력'], colorTheme: '화이트+위키 블루' },

  // ============================================================
  // 71~80: 쇼핑/커머스 계열 / Shopping & Commerce
  // ============================================================
  { id: 71, name: '상품 비교', nameEn: 'Product Compare', concept: '쇼핑몰 상품 비교처럼 비자 유형을 나란히 비교', references: ['Amazon', 'Coupang', 'Best Buy', 'Wirecutter', 'RTINGS'], inputStyle: '상품(비자) 선택 + 필터', resultStyle: '비교 테이블 + 추천 배지', keyFeatures: ['비교 테이블', '별점', '프로/콘 리스트', '최저가 알림'], colorTheme: 'Amazon 오렌지+화이트' },
  { id: 72, name: '구독 플랜', nameEn: 'Subscription Plan', concept: 'SaaS 요금제처럼 비자 경로를 플랜으로 비교', references: ['Stripe Pricing', 'Slack', 'Notion', 'Figma', 'GitHub'], inputStyle: '플랜 선택 + 토글(월/연)', resultStyle: '플랜 비교 카드 + 인기 배지', keyFeatures: ['가격 카드 3단', '인기 배지', '기능 비교 체크', 'CTA 버튼'], colorTheme: '인디고+화이트 SaaS' },
  { id: 73, name: '경매 입찰', nameEn: 'Auction Bidding', concept: '경매처럼 비자 경로에 입찰(우선순위)하며 선택', references: ['eBay', 'Sothebys', 'StockX', 'GOAT', 'Catawiki'], inputStyle: '입찰 금액(우선순위) 입력', resultStyle: '낙찰 결과 + 경매 히스토리', keyFeatures: ['실시간 입찰 UI', '카운트다운', '최고가 표시', '경매 해머'], colorTheme: 'eBay 멀티컬러' },
  { id: 74, name: '장바구니', nameEn: 'Shopping Cart', concept: '장바구니에 조건을 담고 결제(진단)하는 쇼핑 경험', references: ['Shopify', 'WooCommerce', 'Gumroad', 'Lemonsqueezy', 'Paddle'], inputStyle: '카트에 조건 추가 + 수량 조절', resultStyle: '주문 확인서 = 진단 결과', keyFeatures: ['장바구니 카드', '수량 조절', '쿠폰 입력', '결제 요약'], colorTheme: 'Shopify 그린+화이트' },
  { id: 75, name: '음식 배달', nameEn: 'Food Delivery', concept: '배달 앱처럼 비자를 메뉴로 골라 주문하는 경험', references: ['Uber Eats', 'DoorDash', 'Baemin', 'Coupang Eats', 'Grubhub'], inputStyle: '메뉴 선택 + 커스터마이즈', resultStyle: '주문 추적 = 비자 진행 추적', keyFeatures: ['메뉴 카드', '커스터마이즈', '주문 추적', '배달 맵'], colorTheme: '배민 민트+화이트' },
  { id: 76, name: '부동산 매물', nameEn: 'Real Estate', concept: '부동산 앱처럼 비자를 매물처럼 검색하고 비교', references: ['Zillow', 'Redfin', 'Realtor.com', 'Trulia', 'Zigbang'], inputStyle: '지도 검색 + 필터 패널', resultStyle: '매물 리스트 + 상세 비교', keyFeatures: ['지도 핀', '필터 바', '이미지 갤러리', '가격 그래프'], colorTheme: 'Zillow 블루+화이트' },
  { id: 77, name: '패션 코디', nameEn: 'Fashion Styling', concept: '패션 앱처럼 비자 조건을 코디하여 완벽한 조합 만들기', references: ['ZARA', 'H&M', 'ASOS', 'Stitch Fix', 'The RealReal'], inputStyle: '아이템 선택 + 코디 조합', resultStyle: '완성 코디 = 최적 비자 경로', keyFeatures: ['아이템 그리드', '코디 프리뷰', '스타일 태그', 'AI 추천'], colorTheme: '블랙+화이트 패션' },
  { id: 78, name: '중고거래', nameEn: 'Marketplace', concept: '당근마켓/번개장터처럼 비자 경로를 매물로 탐색', references: ['Karrot', 'Mercari', 'Poshmark', 'OfferUp', 'Depop'], inputStyle: '검색 + 동네 설정', resultStyle: '매물 카드 + 채팅 문의', keyFeatures: ['로컬 매물 카드', '가격 정보', '거리 표시', '채팅 버튼'], colorTheme: '당근 오렌지+화이트' },
  { id: 79, name: '렌탈 서비스', nameEn: 'Rental Service', concept: '렌탈 서비스처럼 비자를 기간별로 "임대"하는 느낌', references: ['Rent the Runway', 'Zipcar', 'Turo', 'Fat Llama', 'Grover'], inputStyle: '기간 선택 + 옵션 추가', resultStyle: '렌탈 계약서 스타일 결과', keyFeatures: ['기간 슬라이더', '옵션 추가', '계약서 폼', '비용 계산'], colorTheme: '퍼플+화이트 모던' },
  { id: 80, name: '보험 비교', nameEn: 'Insurance Compare', concept: '보험 비교 사이트처럼 비자 경로를 상품으로 비교', references: ['Lemonade', 'Geico', 'Progressive', 'Oscar Health', 'Metromile'], inputStyle: '간단 정보 + 니즈 선택', resultStyle: '보험 상품 카드 비교', keyFeatures: ['상품 비교 카드', '커버리지 체크', '프리미엄 계산', '추천 배지'], colorTheme: '레모네이드 핑크+화이트' },

  // ============================================================
  // 81~90: 크리에이티브/아트 계열 / Creative & Art
  // ============================================================
  { id: 81, name: '포토 에디터', nameEn: 'Photo Editor', concept: '포토샵처럼 레이어를 쌓아 비자 경로를 구성', references: ['Adobe Photoshop', 'Lightroom', 'VSCO', 'Snapseed', 'Pixlr'], inputStyle: '레이어 패널 + 도구 선택', resultStyle: '완성 이미지 = 비자 경로도', keyFeatures: ['레이어 패널', '도구 팔레트', '캔버스', '히스토리'], colorTheme: 'Adobe 다크+블루' },
  { id: 82, name: '음악 프로듀싱', nameEn: 'Music Producer', concept: 'DAW처럼 트랙을 쌓아 비자 경로를 "작곡"', references: ['Ableton Live', 'Logic Pro', 'FL Studio', 'BandLab', 'Splice'], inputStyle: '트랙 추가 + 클립 배치', resultStyle: '완성 곡 = 비자 타임라인', keyFeatures: ['타임라인 트랙', '웨이브폼', '플레이 버튼', '믹서 패더'], colorTheme: 'Ableton 다크+네온' },
  { id: 83, name: '건축 설계', nameEn: 'Architecture Blueprint', concept: '건축 도면처럼 비자 경로를 설계하고 구조화', references: ['AutoCAD', 'SketchUp', 'Archicad', 'Revit', 'Matterport'], inputStyle: '도면 툴 + 치수 입력', resultStyle: '비자 "건축 도면" 결과', keyFeatures: ['그리드 캔버스', '치수선', '레이어', '3D 프리뷰'], colorTheme: '화이트+블루프린트 블루' },
  { id: 84, name: '영화 시나리오', nameEn: 'Movie Script', concept: '시나리오처럼 장면(Scene)별로 비자 여정을 서술', references: ['Final Draft', 'WriterSolo', 'Arc Studio', 'StudioBinder', 'Celtx'], inputStyle: '씬 작성 + 캐릭터 설정', resultStyle: '시나리오 형태 결과', keyFeatures: ['씬 헤더', '대사 포맷', '장면 전환', '캐릭터 노트'], colorTheme: '화이트+타이프라이터 블랙' },
  { id: 85, name: '만화 스토리보드', nameEn: 'Comic Storyboard', concept: '만화 칸처럼 비자 여정을 스토리보드로 표현', references: ['Webtoon', 'Clip Studio', 'Procreate', 'MediBang', 'Tappytoon'], inputStyle: '칸 선택 + 말풍선 입력', resultStyle: '완성 웹툰 = 비자 여정 만화', keyFeatures: ['만화 칸', '말풍선', '이펙트 라인', '장면 전환'], colorTheme: '화이트+만화 블랙 잉크' },
  { id: 86, name: '패션쇼 런웨이', nameEn: 'Fashion Runway', concept: '패션쇼처럼 비자 경로가 런웨이를 걸어 나오는 쇼 형식', references: ['Vogue', 'SSENSE', 'Net-a-Porter', 'Farfetch', 'Highsnobiety'], inputStyle: '시즌 선택 + 스타일 필터', resultStyle: '런웨이 쇼 형태 결과', keyFeatures: ['런웨이 애니메이션', '모델 카드', '컬렉션 뷰', '에디터 노트'], colorTheme: '블랙+골드 럭셔리' },
  { id: 87, name: '갤러리 전시', nameEn: 'Art Gallery', concept: '아트 갤러리처럼 비자 경로를 작품으로 전시', references: ['Artsy', 'Saatchi Art', 'DeviantArt', 'ArtStation', 'Foundation'], inputStyle: '전시 카탈로그 탐색', resultStyle: '전시 포스터 + 작품 설명', keyFeatures: ['갤러리 뷰', '작품 프레임', '큐레이터 노트', '오디오 가이드'], colorTheme: '미니멀 화이트+아트 액센트' },
  { id: 88, name: 'DJ 믹싱', nameEn: 'DJ Mixing', concept: 'DJ 턴테이블처럼 비자 조건을 믹싱하여 최적 조합 생성', references: ['Serato', 'Traktor', 'rekordbox', 'Mixcloud', 'SoundCloud DJ'], inputStyle: '턴테이블 UI + 크로스페이더', resultStyle: '믹스 결과 + 웨이브폼', keyFeatures: ['턴테이블', '크로스페이더', 'BPM 카운터', '이펙트 노브'], colorTheme: '다크+네온 핑크/시안' },
  { id: 89, name: '인테리어 디자인', nameEn: 'Interior Design', concept: '인테리어 앱처럼 공간(비자 경로)을 꾸미고 배치', references: ['Houzz', 'Havenly', 'RoomSketcher', 'Planner 5D', 'IKEA Place'], inputStyle: '가구(조건) 배치 + 방(경로) 선택', resultStyle: '완성 렌더링 = 비자 경로도', keyFeatures: ['평면도', '3D 뷰', '가구 카탈로그', '무드보드'], colorTheme: '웜 베이지+모던 그레이' },
  { id: 90, name: '네온사인', nameEn: 'Neon Sign', concept: '네온사인 디자이너처럼 빛나는 비자 경로를 디자인', references: ['Custom Neon', 'Canva', 'Adobe Spark', 'Crello', 'VistaCreate'], inputStyle: '네온 글자 입력 + 색상 선택', resultStyle: '완성 네온사인 = 비자 경로', keyFeatures: ['네온 글로우', '컬러 선택', '배경 월', '애니메이션'], colorTheme: '다크 월+네온 멀티컬러' },

  // ============================================================
  // 91~100: 미래/혁신 계열 / Futuristic & Innovation
  // ============================================================
  { id: 91, name: 'AR 카메라', nameEn: 'AR Camera', concept: 'AR 카메라로 문서를 스캔하면 비자 정보를 오버레이', references: ['Apple Vision Pro', 'Snapchat AR', 'Google Lens', 'IKEA Place', 'Pokemon GO'], inputStyle: '카메라 뷰 + AR 오버레이', resultStyle: 'AR 카드 결과 + 3D 오브젝트', keyFeatures: ['카메라 뷰파인더', 'AR 마커', '3D 오브젝트', '스캔 애니메이션'], colorTheme: '투명+화이트 AR' },
  { id: 92, name: '홀로그램', nameEn: 'Hologram', concept: '홀로그램 프로젝터에서 비자 경로가 3D로 떠오르는 UI', references: ['Looking Glass', 'Proto Hologram', 'Microsoft HoloLens', 'Magic Leap', 'Leia Inc'], inputStyle: '3D 오브젝트 회전/선택', resultStyle: '홀로그램 결과 뷰', keyFeatures: ['3D 회전', '글로우 이펙트', '파티클', '투명 카드'], colorTheme: '다크+홀로그래픽 시안' },
  { id: 93, name: '블록체인 지갑', nameEn: 'Blockchain Wallet', concept: '크립토 지갑처럼 비자를 NFT/토큰으로 표현', references: ['MetaMask', 'Phantom', 'Rainbow', 'Zerion', 'OpenSea'], inputStyle: '지갑 연결 + 토큰 선택', resultStyle: 'NFT 카드 결과 + 트랜잭션 기록', keyFeatures: ['지갑 UI', '토큰 그리드', '트랜잭션 리스트', 'QR 코드'], colorTheme: '다크+크립토 퍼플' },
  { id: 94, name: 'AI 어시스턴트', nameEn: 'AI Assistant', concept: 'AI 에이전트가 자율적으로 분석하고 최적 경로를 제안', references: ['Claude', 'ChatGPT', 'Perplexity', 'Copilot', 'Gemini'], inputStyle: 'AI 대화 + 자동 분석', resultStyle: 'AI 리포트 + 인사이트 카드', keyFeatures: ['AI 생성 애니메이션', '소스 인용', '신뢰도 바', '팔로업 질문'], colorTheme: '클린 화이트+AI 퍼플' },
  { id: 95, name: '스마트워치', nameEn: 'Smartwatch', concept: '스마트워치 인터페이스처럼 작고 미니멀한 진단 UI', references: ['Apple Watch', 'Samsung Galaxy Watch', 'Garmin', 'Fitbit', 'Whoop'], inputStyle: '원형 크라운 스크롤 + 탭', resultStyle: '워치 컴플리케이션 결과', keyFeatures: ['원형 UI', '크라운 스크롤', '글랜스 카드', '진동 피드백'], colorTheme: '블랙 OLED+컬러 링' },
  { id: 96, name: '스마트홈', nameEn: 'Smart Home', concept: '스마트홈 앱처럼 비자 조건을 방/기기처럼 제어', references: ['Apple HomeKit', 'Google Home', 'Samsung SmartThings', 'Alexa', 'IFTTT'], inputStyle: '방(카테고리) 선택 + 기기(조건) 토글', resultStyle: '자동화 시나리오 = 비자 경로', keyFeatures: ['방 그리드', '토글 스위치', '자동화 룰', '상태 대시보드'], colorTheme: '다크+스마트 그린' },
  { id: 97, name: '로봇 팩토리', nameEn: 'Robot Factory', concept: '로봇 공장처럼 부품(조건)을 조립하여 비자 로봇을 완성', references: ['Boston Dynamics', 'Tesla Bot', 'NVIDIA Omniverse', 'Unity Robotics', 'ROS'], inputStyle: '부품 선택 + 조립', resultStyle: '완성 로봇 = 비자 경로', keyFeatures: ['부품 카탈로그', '조립 애니메이션', '스펙 시트', '테스트 버튼'], colorTheme: '메탈릭 그레이+로보 블루' },
  { id: 98, name: 'DNA 분석', nameEn: 'DNA Analysis', concept: 'DNA 검사 키트처럼 유전자(조건)를 분석하여 비자 경로 발견', references: ['23andMe', 'AncestryDNA', 'MyHeritage', 'Nebula Genomics', 'Color Health'], inputStyle: '샘플 제출 (정보 입력) + 분석 대기', resultStyle: 'DNA 리포트 = 비자 적합도', keyFeatures: ['DNA 나선 애니메이션', '분석 프로그레스', '유전자 맵', '퍼센티지 차트'], colorTheme: '화이트+바이오 그린/퍼플' },
  { id: 99, name: '타임머신', nameEn: 'Time Machine', concept: '타임머신으로 미래를 미리 보며 비자 경로의 결과를 확인', references: ['Apple Time Machine', 'Internet Archive', 'Wayback Machine', 'Day One', 'Notion Timeline'], inputStyle: '타임라인 스크롤 + 미래 날짜 선택', resultStyle: '미래 시뮬레이션 결과', keyFeatures: ['타임라인 다이얼', '과거↔미래 슬라이더', '시간 워프 효과', '시뮬레이션 뷰'], colorTheme: '다크+시간 골드/시안' },
  { id: 100, name: '잡차자 올인원', nameEn: 'JobChaja All-in-One', concept: '잡차자의 정체성을 담은 최종 진단 페이지 — 비자 매칭 히어로', references: ['JobChaja', 'Toss', 'Linear', 'Vercel', 'Stripe'], inputStyle: '미니멀 스텝 + 스마트 자동완성', resultStyle: '비자 매칭 게이지 + 로드맵 타임라인', keyFeatures: ['비자 매칭 SVG 게이지', '카운트업 숫자', '로드맵 타임라인', '원클릭 CTA'], colorTheme: '잡차자 인디고~퍼플 + 화이트' },
];
