export const VISA_JOURNEY_COPY = {
  ko: {
    eyebrow: '내 비자 여정', title: '한국 체류 준비를 한곳에서',
    intro: '현재 조건 확인부터 준비, 서류, 셀프 수속, 전문가 연결까지 같은 정책 기준으로 이어서 관리하세요.',
    stages: ['자격조건 판단', '조건충족 로드맵', '증빙·신청서류', '셀프 수속', '행정사 상담·대행'],
    stageDescriptions: ['내 정보와 기준을 비교합니다.', '미충족 조건을 갖추는 계획입니다.', '충족한 조건을 증명할 자료입니다.', '본인이 신청하는 순서를 안내합니다.', '정확한 상담이나 대행을 요청합니다.'],
    startTitle: '희망하는 체류 경로를 먼저 알려주세요', startBody: '저장된 결과가 없습니다. 최신 검토 정책이 있는지 확인한 뒤 여정을 시작합니다.',
    targetVisa: '희망 체류자격', pathwayName: '희망 경로 이름', currentVisa: '현재 체류자격', targetDate: '신청 목표일', optional: '선택',
    targetPlaceholder: '희망 체류자격 코드 또는 명칭', pathwayPlaceholder: '내가 알아보기 쉬운 경로 이름', currentPlaceholder: '현재 체류자격 코드 또는 명칭',
    start: '내 비자 여정 시작', starting: '여정을 만드는 중', assessment: '판정 다시 확인', assessing: '확인 중', expert: '행정사에게 확인',
    retry: '다시 시도', loadError: '비자 여정을 불러오지 못했습니다.', emptyStage: '아직 이 단계에 생성된 항목이 없습니다.',
    policyTitle: '이번 안내에 적용된 정책', asOf: '정책 기준', effective: '시행일', reviewed: '전문가 검토', evaluated: '결과 계산', version: '정책 버전', source: '공식 근거',
    current: '최신', upcoming: '시행 예정 변경 있음', reviewing: '정책 변경 검토 중', overdue: '검토기한 경과', unavailable: '근거 확인 필요', unknown: '최신성 확인 필요',
    requirementSummary: '조건별 판정', roadmapSummary: '조건을 갖추기 위한 작업', evidenceSummary: '조건을 증명할 서류', procedureSummary: '본인이 진행할 수속 순서', expertSummary: '전문가 도움 요청',
    currentValue: '현재', targetValue: '목표', owner: '담당', due: '권장 완료', expected: '예상 완료', issuer: '발급처', format: '제출 형식', validUntil: '유효기한', channel: '신청 경로',
    blockedDependency: '선행 단계가 완료되어야 진행할 수 있습니다.', officialSite: '공식 사이트 열기',
    serviceType: '필요한 도움', consult: '조건·경로 상담', review: '준비서류 검토', agency: '신청 대행 문의', question: '질문 또는 요청사항', questionPlaceholder: '행정사에게 확인받고 싶은 내용을 적어주세요.',
    consent: '선택한 행정사에게 이 여정의 입력정보, 판정 근거와 준비 현황을 제공하는 데 동의합니다.', consentHint: '동의하기 전 전달 범위와 개인정보 처리 안내를 확인하세요.',
    requestExpert: '상담 요청 보내기', requesting: '요청 중', existingCases: '진행 중인 전문가 요청', expertSuccess: '전문가 요청이 접수되었습니다.',
    legalTitle: '이 서비스의 안내 범위', legalBody: '잡차자는 공개된 정책에 근거한 일반 정보와 준비 보조를 제공합니다. 체류자격 발급을 대리하거나 허가를 보장하지 않습니다. 개인별 사실관계에 대한 정확한 판단은 출입국민원 1345 또는 자격이 확인된 행정사와 직접 상담해 확인하세요.',
    privacy: '전문가 연결 전에는 입력정보가 행정사에게 전달되지 않습니다.', noPolicy: '적용 정책 정보를 확인 중입니다. 정책 정보가 확인되기 전에는 확정 결과로 이용하지 마세요.',
    noGuarantee: '입력정보 기준의 판단 보조 결과이며 실제 허가 여부와 다를 수 있습니다.',
    inputTitle: '판정에 필요한 정보', inputBody: '희망 회사가 정해지지 않았다면 모르는 값은 비워둘 수 있습니다. 빈 값은 추정하지 않고 정보 부족으로 표시합니다.',
    inputMissing: '아직 입력이 필요한 항목', saveAssessment: '입력정보로 판단 보조 받기',
    fields: { ksicCode: '회사 업종코드(KSIC)', companySizeType: '회사 규모 유형', employeeCountKorean: '한국인 직원 수', employeeCountForeign: '외국인 직원 수', annualRevenue: '연매출(만원)', addressRoad: '근무지 도로명주소', jobType: '고용 형태', offeredSalary: '제안 월급(만원)', nationality: '국적 코드', age: '나이', educationLevel: '최종 학력', koreanLevel: '한국어 수준', workExperienceYears: '관련 경력(년)', currentVisaCode: '현재 체류자격', targetOccupationCode: '희망 직종코드' },
    requirementStatuses: { SATISFIED: '충족', IMPROVABLE: '개선 가능', TIME_DEPENDENT: '시간 필요', COMPANY_ACTION_REQUIRED: '회사 조치 필요', NOT_REMEDIABLE: '현재 경로에서 해소 어려움', INSUFFICIENT_DATA: '정보 부족', EXPERT_REVIEW_REQUIRED: '전문가 확인 필요' },
    progressStatuses: { NOT_STARTED: '준비 전', IN_PROGRESS: '진행 중', COMPLETED: '완료', BLOCKED: '진행 불가', NOT_APPLICABLE: '해당 없음' },
  },
  en: {
    eyebrow: 'My visa journey', title: 'Plan your stay in Korea in one place',
    intro: 'Keep eligibility, gap actions, evidence, self-filing steps, and expert support connected to the same policy version.',
    stages: ['Eligibility check', 'Eligibility roadmap', 'Evidence & forms', 'Self-filing steps', 'Expert help'],
    stageDescriptions: ['Compare your facts with the rules.', 'Work on unmet eligibility conditions.', 'Prepare proof of conditions you meet.', 'Follow the steps to file yourself.', 'Request case-specific advice or representation.'],
    startTitle: 'Tell us your intended stay pathway', startBody: 'No saved journey was found. We will check for the latest reviewed policy before starting.',
    targetVisa: 'Target status of stay', pathwayName: 'Pathway name', currentVisa: 'Current status of stay', targetDate: 'Target filing date', optional: 'Optional',
    targetPlaceholder: 'Enter the target status code or name', pathwayPlaceholder: 'Give this pathway a helpful name', currentPlaceholder: 'Enter your current status code or name',
    start: 'Start my visa journey', starting: 'Creating your journey', assessment: 'Check assessment again', assessing: 'Checking', expert: 'Ask an administrative agent',
    retry: 'Try again', loadError: 'We could not load your visa journey.', emptyStage: 'No items have been created for this stage yet.',
    policyTitle: 'Policy used for this guidance', asOf: 'Policy as of', effective: 'Effective from', reviewed: 'Expert reviewed', evaluated: 'Evaluated', version: 'Policy version', source: 'Official source',
    current: 'Current', upcoming: 'Upcoming change', reviewing: 'Policy change under review', overdue: 'Review overdue', unavailable: 'Source needs verification', unknown: 'Freshness not verified',
    requirementSummary: 'Eligibility by requirement', roadmapSummary: 'Actions to meet eligibility', evidenceSummary: 'Evidence and application forms', procedureSummary: 'Steps to file by yourself', expertSummary: 'Request expert support',
    currentValue: 'Current', targetValue: 'Target', owner: 'Owner', due: 'Recommended by', expected: 'Expected completion', issuer: 'Issuer', format: 'Submission format', validUntil: 'Valid until', channel: 'Filing channel',
    blockedDependency: 'Complete the prerequisite step first.', officialSite: 'Open official site',
    serviceType: 'Support needed', consult: 'Eligibility consultation', review: 'Document review', agency: 'Filing representation inquiry', question: 'Question or request', questionPlaceholder: 'Describe what you want the administrative agent to review.',
    consent: 'I agree to share my journey inputs, assessment grounds, and preparation progress with the selected administrative agent.', consentHint: 'Review the sharing scope and privacy notice before agreeing.',
    requestExpert: 'Send consultation request', requesting: 'Sending request', existingCases: 'Current expert requests', expertSuccess: 'Your expert request was submitted.',
    legalTitle: 'Scope of this guidance', legalBody: 'JobChaja provides general information and preparation support based on published policy. It does not file on your behalf or guarantee approval. For an exact assessment of your circumstances, consult Immigration Contact Center 1345 or a credential-verified administrative agent directly.',
    privacy: 'Your inputs are not shared with an administrative agent until you consent.', noPolicy: 'We are verifying the applicable policy. Do not treat this as a definitive result until policy information is available.',
    noGuarantee: 'This is decision support based on your inputs and may differ from the actual immigration decision.',
    inputTitle: 'Information needed for assessment', inputBody: 'If you have not chosen an employer yet, you may leave unknown values blank. Missing values are never guessed and will be shown as insufficient information.',
    inputMissing: 'Information still needed', saveAssessment: 'Assess using these details',
    fields: { ksicCode: 'Company industry code (KSIC)', companySizeType: 'Company size type', employeeCountKorean: 'Korean employee count', employeeCountForeign: 'Foreign employee count', annualRevenue: 'Annual revenue (KRW 10,000)', addressRoad: 'Workplace road address', jobType: 'Employment type', offeredSalary: 'Offered monthly salary (KRW 10,000)', nationality: 'Nationality code', age: 'Age', educationLevel: 'Highest education', koreanLevel: 'Korean proficiency', workExperienceYears: 'Relevant experience (years)', currentVisaCode: 'Current status of stay', targetOccupationCode: 'Target occupation code' },
    requirementStatuses: { SATISFIED: 'Satisfied', IMPROVABLE: 'Can be improved', TIME_DEPENDENT: 'Needs time', COMPANY_ACTION_REQUIRED: 'Company action needed', NOT_REMEDIABLE: 'Not remediable on this pathway', INSUFFICIENT_DATA: 'More information needed', EXPERT_REVIEW_REQUIRED: 'Expert review needed' },
    progressStatuses: { NOT_STARTED: 'Not started', IN_PROGRESS: 'In progress', COMPLETED: 'Completed', BLOCKED: 'Blocked', NOT_APPLICABLE: 'Not applicable' },
  },
} as const;

export type VisaJourneyCopy = typeof VISA_JOURNEY_COPY.ko | typeof VISA_JOURNEY_COPY.en;
