/**
 * 알바 채용관 Variant C 목업 데이터
 * Mock data for Alba recruitment Variant C
 */

import type {
  AlbaJobResponse,
  VisaEvalResult,
  MatchingSummary,
} from './alba-types';

// 비자 매칭 결과 목업 / Visa matching result mock
export const MOCK_VISA_ELIGIBLE: VisaEvalResult[] = [
  {
    visaCode: 'F-5',
    visaName: '영주',
    visaNameEn: 'Permanent Residence',
    status: 'eligible',
    notes: '내국인과 동일한 취업 권리',
  },
  {
    visaCode: 'F-6',
    visaName: '결혼이민',
    visaNameEn: 'Marriage Immigration',
    status: 'eligible',
    notes: '내국인과 동일한 취업 권리',
  },
  {
    visaCode: 'F-2',
    visaName: '거주',
    visaNameEn: 'Residence',
    status: 'eligible',
    notes: '취업 제한 없음',
  },
  {
    visaCode: 'H-1',
    visaName: '워킹홀리데이',
    visaNameEn: 'Working Holiday',
    status: 'eligible',
    notes: '체류기간 최대 1년, 18~30세 대상',
  },
];

export const MOCK_VISA_CONDITIONAL: VisaEvalResult[] = [
  {
    visaCode: 'D-2',
    visaName: '유학',
    visaNameEn: 'Study Abroad',
    status: 'conditional',
    conditions: [
      '주말 근무만 가능 (평일 포함 시 TOPIK 3급+ 필요)',
      '체류자격외활동허가 필요',
    ],
    maxWeeklyHours: 30,
    maxWorkplaces: 2,
    requiredPermit: '체류자격외활동허가',
  },
  {
    visaCode: 'H-2',
    visaName: '방문취업',
    visaNameEn: 'Visit & Employment',
    status: 'conditional',
    conditions: ['특례고용허가 필요 (일부 업종)'],
    requiredPermit: '특례고용허가',
  },
  {
    visaCode: 'F-4',
    visaName: '재외동포',
    visaNameEn: 'Overseas Korean',
    status: 'conditional',
    conditions: ['단순노무 해당 시 예외 직종 확인 필요'],
  },
];

export const MOCK_VISA_BLOCKED: VisaEvalResult[] = [
  {
    visaCode: 'C-3',
    visaName: '단기방문',
    visaNameEn: 'Short-term Visit',
    status: 'blocked',
    blockReasons: ['취업 활동 불가 비자'],
  },
  {
    visaCode: 'B-1',
    visaName: '사증면제',
    visaNameEn: 'Visa Exemption',
    status: 'blocked',
    blockReasons: ['취업 활동 불가 비자'],
  },
];

export const MOCK_MATCHING_SUMMARY: MatchingSummary = {
  totalEligible: 4,
  totalConditional: 3,
  totalBlocked: 2,
};

// 공고 목록 목업 / Job listing mock data
export const MOCK_ALBA_JOBS: AlbaJobResponse[] = [
  {
    jobId: '10001',
    corporateId: '67890',
    boardType: 'PART_TIME',
    tierType: 'PREMIUM',
    title: '강남역 근처 카페 주말 바리스타 모집',
    status: 'ACTIVE',
    jobCategoryCode: 'CAFE_BARISTA',
    jobCategoryName: '카페 바리스타',
    ksicCode: 'I',
    jobDescription: '주말 런치 바리스타 업무',
    recruitCount: 2,
    hourlyWage: 12000,
    weeklyHours: 16,
    schedule: [
      { dayOfWeek: 'SAT', startTime: '10:00', endTime: '18:00' },
      { dayOfWeek: 'SUN', startTime: '10:00', endTime: '18:00' },
    ],
    isWeekendOnly: true,
    workPeriod: { startDate: '2026-03-01', endDate: '2026-08-31' },
    address: { sido: '서울특별시', sigungu: '강남구', detail: '역삼동 123-45 2층', lat: 37.4979, lng: 127.0276 },
    displayAddress: '서울 강남구 역삼동',
    koreanLevel: 'BASIC',
    experienceLevel: 'NONE',
    preferredQualifications: '바리스타 자격증 우대',
    benefits: ['MEAL', 'TRANSPORT'],
    detailDescription: '주말 런치 타임 바리스타 업무를 담당합니다.',
    workContentImg: null,
    applicationDeadline: '2026-03-15',
    applicationMethod: 'PLATFORM',
    contactName: '김카페',
    contactPhone: '010-1234-5678',
    contactEmail: 'hire@cafe.com',
    isPremium: true,
    premiumStartAt: '2026-02-15T00:00:00Z',
    premiumEndAt: '2026-03-01T00:00:00Z',
    matchedVisas: [...MOCK_VISA_ELIGIBLE, ...MOCK_VISA_CONDITIONAL],
    allowedVisas: 'F-5,F-6,F-2,H-1,D-2,H-2,F-4',
    viewCount: 342,
    scrapCount: 28,
    applyCount: 12,
    companyName: '카페 라떼',
    companyLogo: null,
    createdAt: '2026-02-10T09:00:00Z',
    updatedAt: '2026-02-15T09:00:00Z',
    expiresAt: '2026-02-24T09:00:00Z',
  },
  {
    jobId: '10002',
    corporateId: '67891',
    boardType: 'PART_TIME',
    tierType: 'STANDARD',
    title: '홍대 편의점 야간 알바 구함',
    status: 'ACTIVE',
    jobCategoryCode: 'CONV_STORE',
    jobCategoryName: '편의점',
    ksicCode: 'G',
    jobDescription: '야간 편의점 근무',
    recruitCount: 1,
    hourlyWage: 11500,
    weeklyHours: 25,
    schedule: [
      { dayOfWeek: 'MON', startTime: '22:00', endTime: '06:00' },
      { dayOfWeek: 'WED', startTime: '22:00', endTime: '06:00' },
      { dayOfWeek: 'FRI', startTime: '22:00', endTime: '06:00' },
    ],
    isWeekendOnly: false,
    workPeriod: { startDate: '2026-03-01', endDate: null },
    address: { sido: '서울특별시', sigungu: '마포구', detail: '서교동 456-78', lat: 37.5565, lng: 126.9237 },
    displayAddress: '서울 마포구 서교동',
    koreanLevel: 'DAILY',
    experienceLevel: 'NONE',
    preferredQualifications: null,
    benefits: ['MEAL', 'INSURANCE'],
    detailDescription: '야간 편의점 근무입니다. 성실한 분 환영합니다.',
    workContentImg: null,
    applicationDeadline: null,
    applicationMethod: 'PLATFORM',
    contactName: '이편의',
    contactPhone: '010-2345-6789',
    contactEmail: null,
    isPremium: false,
    premiumStartAt: null,
    premiumEndAt: null,
    matchedVisas: [...MOCK_VISA_ELIGIBLE.slice(0, 2), ...MOCK_VISA_CONDITIONAL.slice(0, 1)],
    allowedVisas: 'F-5,F-6,D-2',
    viewCount: 156,
    scrapCount: 14,
    applyCount: 5,
    companyName: 'CU 홍대입구점',
    companyLogo: null,
    createdAt: '2026-02-12T14:00:00Z',
    updatedAt: '2026-02-12T14:00:00Z',
    expiresAt: '2026-02-26T14:00:00Z',
  },
  {
    jobId: '10003',
    corporateId: '67892',
    boardType: 'PART_TIME',
    tierType: 'PREMIUM',
    title: '이태원 이탈리안 레스토랑 서빙 직원 모집',
    status: 'ACTIVE',
    jobCategoryCode: 'REST_SERVING',
    jobCategoryName: '음식점 서빙',
    ksicCode: 'I',
    jobDescription: '디너타임 홀서빙',
    recruitCount: 3,
    hourlyWage: 13000,
    weeklyHours: 20,
    schedule: [
      { dayOfWeek: 'THU', startTime: '17:00', endTime: '22:00' },
      { dayOfWeek: 'FRI', startTime: '17:00', endTime: '22:00' },
      { dayOfWeek: 'SAT', startTime: '17:00', endTime: '22:00' },
      { dayOfWeek: 'SUN', startTime: '12:00', endTime: '17:00' },
    ],
    isWeekendOnly: false,
    workPeriod: { startDate: '2026-03-01', endDate: '2026-09-30' },
    address: { sido: '서울특별시', sigungu: '용산구', detail: '이태원동 123', lat: 37.5346, lng: 126.9946 },
    displayAddress: '서울 용산구 이태원동',
    koreanLevel: 'DAILY',
    experienceLevel: 'UNDER_1Y',
    preferredQualifications: '영어 가능자 우대, 서빙 경험자 우대',
    benefits: ['MEAL', 'TRANSPORT', 'STAFF_DISCOUNT'],
    detailDescription: '이태원 유명 이탈리안 레스토랑에서 서빙 직원을 모집합니다.',
    workContentImg: null,
    applicationDeadline: '2026-03-20',
    applicationMethod: 'PLATFORM',
    contactName: '박매니저',
    contactPhone: '010-3456-7890',
    contactEmail: 'manager@restaurant.com',
    isPremium: true,
    premiumStartAt: '2026-02-14T00:00:00Z',
    premiumEndAt: '2026-02-28T00:00:00Z',
    matchedVisas: [...MOCK_VISA_ELIGIBLE, ...MOCK_VISA_CONDITIONAL],
    allowedVisas: 'F-5,F-6,F-2,H-1,D-2,H-2,F-4',
    viewCount: 521,
    scrapCount: 45,
    applyCount: 18,
    companyName: 'Trattoria Milano',
    companyLogo: null,
    createdAt: '2026-02-08T10:00:00Z',
    updatedAt: '2026-02-14T10:00:00Z',
    expiresAt: '2026-02-22T10:00:00Z',
  },
  {
    jobId: '10004',
    corporateId: '67893',
    boardType: 'PART_TIME',
    tierType: 'STANDARD',
    title: '안산 반월공단 포장 알바',
    status: 'ACTIVE',
    jobCategoryCode: 'FACTORY',
    jobCategoryName: '공장/제조',
    ksicCode: 'C',
    jobDescription: '제품 포장 및 검수',
    recruitCount: 5,
    hourlyWage: 11000,
    weeklyHours: 40,
    schedule: [
      { dayOfWeek: 'MON', startTime: '09:00', endTime: '18:00' },
      { dayOfWeek: 'TUE', startTime: '09:00', endTime: '18:00' },
      { dayOfWeek: 'WED', startTime: '09:00', endTime: '18:00' },
      { dayOfWeek: 'THU', startTime: '09:00', endTime: '18:00' },
      { dayOfWeek: 'FRI', startTime: '09:00', endTime: '18:00' },
    ],
    isWeekendOnly: false,
    workPeriod: { startDate: '2026-03-01', endDate: null },
    address: { sido: '경기도', sigungu: '안산시', detail: '반월공단 456', lat: 37.3219, lng: 126.8309 },
    displayAddress: '경기 안산시 반월공단',
    koreanLevel: 'NONE',
    experienceLevel: 'NONE',
    preferredQualifications: null,
    benefits: ['MEAL', 'TRANSPORT', 'INSURANCE', 'HOUSING'],
    detailDescription: '제품 포장 및 검수 업무를 담당합니다. 숙소 제공 가능.',
    workContentImg: null,
    applicationDeadline: null,
    applicationMethod: 'PHONE',
    contactName: '최공장',
    contactPhone: '031-123-4567',
    contactEmail: null,
    isPremium: false,
    premiumStartAt: null,
    premiumEndAt: null,
    matchedVisas: [MOCK_VISA_ELIGIBLE[0], MOCK_VISA_ELIGIBLE[1]],
    allowedVisas: 'F-5,F-6',
    viewCount: 89,
    scrapCount: 7,
    applyCount: 3,
    companyName: '한우리 패키징',
    companyLogo: null,
    createdAt: '2026-02-16T08:00:00Z',
    updatedAt: '2026-02-16T08:00:00Z',
    expiresAt: '2026-03-02T08:00:00Z',
  },
  {
    jobId: '10005',
    corporateId: '67894',
    boardType: 'PART_TIME',
    tierType: 'STANDARD',
    title: '신촌 서점 판매 알바',
    status: 'ACTIVE',
    jobCategoryCode: 'MART_STAFF',
    jobCategoryName: '마트/매장',
    ksicCode: 'G',
    jobDescription: '서점 판매 및 정리',
    recruitCount: 1,
    hourlyWage: 10500,
    weeklyHours: 15,
    schedule: [
      { dayOfWeek: 'SAT', startTime: '13:00', endTime: '20:00' },
      { dayOfWeek: 'SUN', startTime: '13:00', endTime: '21:00' },
    ],
    isWeekendOnly: true,
    workPeriod: { startDate: '2026-03-01', endDate: '2026-06-30' },
    address: { sido: '서울특별시', sigungu: '서대문구', detail: '창천동 12-3', lat: 37.5598, lng: 126.9368 },
    displayAddress: '서울 서대문구 신촌',
    koreanLevel: 'DAILY',
    experienceLevel: 'NONE',
    preferredQualifications: '책 좋아하시는 분 환영',
    benefits: ['STAFF_DISCOUNT'],
    detailDescription: '서점 판매 및 도서 정리 업무를 담당합니다.',
    workContentImg: null,
    applicationDeadline: '2026-03-10',
    applicationMethod: 'PLATFORM',
    contactName: '정서점',
    contactPhone: '010-4567-8901',
    contactEmail: 'books@store.com',
    isPremium: false,
    premiumStartAt: null,
    premiumEndAt: null,
    matchedVisas: [...MOCK_VISA_ELIGIBLE, ...MOCK_VISA_CONDITIONAL.slice(0, 2)],
    allowedVisas: 'F-5,F-6,F-2,H-1,D-2,H-2',
    viewCount: 203,
    scrapCount: 19,
    applyCount: 8,
    companyName: '인디 서점',
    companyLogo: null,
    createdAt: '2026-02-13T11:00:00Z',
    updatedAt: '2026-02-13T11:00:00Z',
    expiresAt: '2026-02-27T11:00:00Z',
  },
  {
    jobId: '10006',
    corporateId: '67890',
    boardType: 'PART_TIME',
    tierType: 'STANDARD',
    title: '강남역 카페 평일 오후 바리스타',
    status: 'CLOSED',
    jobCategoryCode: 'CAFE_BARISTA',
    jobCategoryName: '카페 바리스타',
    ksicCode: 'I',
    jobDescription: '평일 오후 바리스타 업무',
    recruitCount: 1,
    hourlyWage: 11000,
    weeklyHours: 20,
    schedule: [
      { dayOfWeek: 'MON', startTime: '14:00', endTime: '18:00' },
      { dayOfWeek: 'TUE', startTime: '14:00', endTime: '18:00' },
      { dayOfWeek: 'WED', startTime: '14:00', endTime: '18:00' },
      { dayOfWeek: 'THU', startTime: '14:00', endTime: '18:00' },
      { dayOfWeek: 'FRI', startTime: '14:00', endTime: '18:00' },
    ],
    isWeekendOnly: false,
    workPeriod: { startDate: '2026-01-15', endDate: '2026-03-15' },
    address: { sido: '서울특별시', sigungu: '강남구', detail: '역삼동 123-45', lat: 37.4979, lng: 127.0276 },
    displayAddress: '서울 강남구 역삼동',
    koreanLevel: 'BASIC',
    experienceLevel: 'NONE',
    preferredQualifications: null,
    benefits: ['MEAL'],
    detailDescription: '평일 오후 바리스타 업무.',
    workContentImg: null,
    applicationDeadline: '2026-02-01',
    applicationMethod: 'PLATFORM',
    contactName: '김카페',
    contactPhone: '010-1234-5678',
    contactEmail: null,
    isPremium: false,
    premiumStartAt: null,
    premiumEndAt: null,
    matchedVisas: [...MOCK_VISA_ELIGIBLE.slice(0, 3)],
    allowedVisas: 'F-5,F-6,F-2',
    viewCount: 87,
    scrapCount: 5,
    applyCount: 2,
    companyName: '카페 라떼',
    companyLogo: null,
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-02-01T12:00:00Z',
    expiresAt: '2026-01-24T09:00:00Z',
  },
];

// 프리미엄 공고만 추출 / Premium jobs only
export const MOCK_PREMIUM_JOBS = MOCK_ALBA_JOBS.filter((j) => j.isPremium);
