/**
 * 알바 채용관 Variant D 목업 데이터
 * Alba recruitment Variant D mock data
 *
 * 실제 API 연동 전 시안 확인용 더미 데이터
 * Dummy data for design variant preview before actual API integration
 */

import type {
  AlbaJobResponse,
  AlbaJobSearchItem,
  VisaEvalResult,
  VisaMatchingResponse,
} from './alba-types';

// ─── 비자 매칭 결과 목업 / Visa matching result mock ───

export const MOCK_VISA_MATCHING_RESPONSE: VisaMatchingResponse = {
  eligible: [
    {
      visaCode: 'F-5',
      visaName: '영주',
      visaNameEn: 'Permanent Residence',
      status: 'eligible',
      notes: '내국인과 동일한 취업 권리',
      requiredPermit: null,
      maxWeeklyHours: null,
      maxWorkplaces: null,
    },
    {
      visaCode: 'F-6',
      visaName: '결혼이민',
      visaNameEn: 'Marriage Immigration',
      status: 'eligible',
      notes: '내국인과 동일한 취업 권리',
      requiredPermit: null,
      maxWeeklyHours: null,
      maxWorkplaces: null,
    },
    {
      visaCode: 'F-2',
      visaName: '거주',
      visaNameEn: 'Residence',
      status: 'eligible',
      notes: '취업 제한 없음',
      requiredPermit: null,
      maxWeeklyHours: null,
      maxWorkplaces: null,
    },
    {
      visaCode: 'H-1',
      visaName: '워킹홀리데이',
      visaNameEn: 'Working Holiday',
      status: 'eligible',
      notes: '체류기간 최대 1년, 18~30세 대상',
      requiredPermit: null,
      maxWeeklyHours: null,
      maxWorkplaces: null,
    },
  ],
  conditional: [
    {
      visaCode: 'D-2',
      visaName: '유학',
      visaNameEn: 'Study Abroad',
      status: 'conditional',
      conditions: [
        '주말 근무만 가능 (평일 포함 시 TOPIK 3급+ 필요)',
        '체류자격외활동허가 필요',
      ],
      maxWeeklyHours: 30,
      maxWorkplaces: 2,
      requiredPermit: '체류자격외활동허가',
      notes: null,
    },
    {
      visaCode: 'H-2',
      visaName: '방문취업',
      visaNameEn: 'Visit & Employment',
      status: 'conditional',
      conditions: ['특례고용허가 필요 (일부 업종)'],
      requiredPermit: '특례고용허가',
      maxWeeklyHours: null,
      maxWorkplaces: null,
      notes: null,
    },
    {
      visaCode: 'F-4',
      visaName: '재외동포',
      visaNameEn: 'Overseas Korean',
      status: 'conditional',
      conditions: ['단순노무 해당 시 예외 직종 확인 필요'],
      requiredPermit: null,
      maxWeeklyHours: null,
      maxWorkplaces: null,
      notes: null,
    },
  ],
  blocked: [
    {
      visaCode: 'C-3',
      visaName: '단기방문',
      visaNameEn: 'Short-term Visit',
      status: 'blocked',
      blockReasons: ['취업 활동 불가 비자'],
      requiredPermit: null,
      maxWeeklyHours: null,
      maxWorkplaces: null,
      notes: null,
    },
    {
      visaCode: 'B-1',
      visaName: '사증면제',
      visaNameEn: 'Visa Exemption',
      status: 'blocked',
      blockReasons: ['취업 활동 불가 비자'],
      requiredPermit: null,
      maxWeeklyHours: null,
      maxWorkplaces: null,
      notes: null,
    },
  ],
  summary: {
    totalEligible: 4,
    totalConditional: 3,
    totalBlocked: 2,
  },
  matchedAt: '2026-02-18T12:00:00Z',
  inputSummary: {
    jobCategoryCode: 'REST_SERVING',
    ksicCode: 'I',
    weeklyHours: 20,
    isWeekendOnly: true,
    hasWeekdayShift: false,
    isDepopulationArea: false,
  },
};

// ─── 기업용 알바 공고 목록 목업 / Company alba job list mock ───

export const MOCK_COMPANY_JOBS: AlbaJobResponse[] = [
  {
    jobId: '10001',
    corporateId: '67890',
    boardType: 'PART_TIME',
    tierType: 'PREMIUM',
    title: '강남역 근처 카페 주말 바리스타 모집',
    status: 'ACTIVE',
    jobCategoryCode: 'CAFE_BARISTA',
    jobCategoryName: '카페 바리스타',
    ksicCode: 'I',
    jobDescription: '주말 런치 서빙 및 정리',
    recruitCount: 2,
    hourlyWage: 12000,
    weeklyHours: 20,
    schedule: [
      { dayOfWeek: 'SAT', startTime: '12:00', endTime: '22:00' },
      { dayOfWeek: 'SUN', startTime: '12:00', endTime: '22:00' },
    ],
    isWeekendOnly: true,
    workPeriod: { startDate: '2026-03-01', endDate: '2026-06-30' },
    address: { sido: '서울특별시', sigungu: '강남구', detail: '역삼동 123-45 2층', lat: 37.4979, lng: 127.0276 },
    displayAddress: '서울 강남구 역삼동',
    koreanLevel: 'BASIC',
    experienceLevel: 'NONE',
    preferredQualifications: '바리스타 자격증 우대',
    benefits: ['MEAL', 'TRANSPORT'],
    detailDescription: '주말 런치 타임(11시~15시) 서빙 및 마감 정리를 담당합니다.',
    workContentImg: null,
    applicationDeadline: '2026-03-15',
    applicationMethod: 'PLATFORM',
    contactName: '김채용',
    contactPhone: '010-1234-5678',
    contactEmail: 'hire@cafe.com',
    isPremium: true,
    premiumStartAt: '2026-02-18T00:00:00Z',
    premiumEndAt: '2026-03-04T00:00:00Z',
    matchedVisas: [...MOCK_VISA_MATCHING_RESPONSE.eligible, ...MOCK_VISA_MATCHING_RESPONSE.conditional],
    allowedVisas: 'F-5,F-6,F-2,H-1,D-2,H-2,F-4',
    viewCount: 128,
    scrapCount: 34,
    applyCount: 12,
    companyName: '카페 라떼',
    companyLogo: null,
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-02-18T10:00:00Z',
    expiresAt: '2026-03-01T09:00:00Z',
  },
  {
    jobId: '10002',
    corporateId: '67890',
    boardType: 'PART_TIME',
    tierType: 'STANDARD',
    title: '이태원 레스토랑 평일 서빙 알바',
    status: 'ACTIVE',
    jobCategoryCode: 'REST_SERVING',
    jobCategoryName: '음식점 서빙',
    ksicCode: 'I',
    jobDescription: '평일 런치 디너 서빙',
    recruitCount: 1,
    hourlyWage: 11000,
    weeklyHours: 25,
    schedule: [
      { dayOfWeek: 'MON', startTime: '11:00', endTime: '16:00' },
      { dayOfWeek: 'WED', startTime: '11:00', endTime: '16:00' },
      { dayOfWeek: 'FRI', startTime: '11:00', endTime: '16:00' },
      { dayOfWeek: 'SAT', startTime: '11:00', endTime: '16:00' },
      { dayOfWeek: 'SUN', startTime: '11:00', endTime: '16:00' },
    ],
    isWeekendOnly: false,
    workPeriod: { startDate: '2026-03-10', endDate: null },
    address: { sido: '서울특별시', sigungu: '용산구', detail: '이태원동 45-7', lat: 37.5345, lng: 126.9946 },
    displayAddress: '서울 용산구 이태원동',
    koreanLevel: 'DAILY',
    experienceLevel: 'UNDER_1Y',
    preferredQualifications: null,
    benefits: ['MEAL', 'INSURANCE'],
    detailDescription: '이태원 이탈리안 레스토랑에서 서빙 담당자를 모집합니다.',
    workContentImg: null,
    applicationDeadline: null,
    applicationMethod: 'PLATFORM',
    contactName: '이매니저',
    contactPhone: '010-9876-5432',
    contactEmail: null,
    isPremium: false,
    premiumStartAt: null,
    premiumEndAt: null,
    matchedVisas: MOCK_VISA_MATCHING_RESPONSE.eligible,
    allowedVisas: 'F-5,F-6,F-2,H-1',
    viewCount: 56,
    scrapCount: 12,
    applyCount: 5,
    companyName: '카페 라떼',
    companyLogo: null,
    createdAt: '2026-02-10T09:00:00Z',
    updatedAt: '2026-02-10T09:00:00Z',
    expiresAt: '2026-02-24T09:00:00Z',
  },
  {
    jobId: '10003',
    corporateId: '67890',
    boardType: 'PART_TIME',
    tierType: 'STANDARD',
    title: '홍대 편의점 야간 근무',
    status: 'PAUSED',
    jobCategoryCode: 'CONV_STORE',
    jobCategoryName: '편의점',
    ksicCode: 'G',
    jobDescription: '야간 편의점 운영 및 재고관리',
    recruitCount: 1,
    hourlyWage: 13000,
    weeklyHours: 30,
    schedule: [
      { dayOfWeek: 'MON', startTime: '22:00', endTime: '06:00' },
      { dayOfWeek: 'TUE', startTime: '22:00', endTime: '06:00' },
      { dayOfWeek: 'WED', startTime: '22:00', endTime: '06:00' },
    ],
    isWeekendOnly: false,
    workPeriod: { startDate: '2026-02-01', endDate: '2026-05-31' },
    address: { sido: '서울특별시', sigungu: '마포구', detail: '서교동 321-1', lat: 37.5563, lng: 126.9236 },
    displayAddress: '서울 마포구 서교동',
    koreanLevel: 'BASIC',
    experienceLevel: 'NONE',
    preferredQualifications: null,
    benefits: ['MEAL'],
    detailDescription: '홍대 인근 편의점 야간 파트타임 구합니다.',
    workContentImg: null,
    applicationDeadline: '2026-03-01',
    applicationMethod: 'PHONE',
    contactName: '박점장',
    contactPhone: '010-5555-6666',
    contactEmail: null,
    isPremium: false,
    premiumStartAt: null,
    premiumEndAt: null,
    matchedVisas: MOCK_VISA_MATCHING_RESPONSE.eligible,
    allowedVisas: 'F-5,F-6,F-2,H-1',
    viewCount: 89,
    scrapCount: 22,
    applyCount: 8,
    companyName: '카페 라떼',
    companyLogo: null,
    createdAt: '2026-02-05T09:00:00Z',
    updatedAt: '2026-02-12T14:00:00Z',
    expiresAt: '2026-02-19T09:00:00Z',
  },
  {
    jobId: '10004',
    corporateId: '67890',
    boardType: 'PART_TIME',
    tierType: 'STANDARD',
    title: '성수동 카페 오픈 스탭',
    status: 'CLOSED',
    jobCategoryCode: 'CAFE_BARISTA',
    jobCategoryName: '카페 바리스타',
    ksicCode: 'I',
    jobDescription: '카페 오픈 시간대 준비 및 운영',
    recruitCount: 2,
    hourlyWage: 11500,
    weeklyHours: 15,
    schedule: [
      { dayOfWeek: 'TUE', startTime: '07:00', endTime: '12:00' },
      { dayOfWeek: 'THU', startTime: '07:00', endTime: '12:00' },
      { dayOfWeek: 'SAT', startTime: '07:00', endTime: '12:00' },
    ],
    isWeekendOnly: false,
    workPeriod: { startDate: '2026-01-15', endDate: '2026-03-15' },
    address: { sido: '서울특별시', sigungu: '성동구', detail: '성수동2가 278-8', lat: 37.5445, lng: 127.0562 },
    displayAddress: '서울 성동구 성수동',
    koreanLevel: 'NONE',
    experienceLevel: 'NONE',
    preferredQualifications: null,
    benefits: ['MEAL', 'STAFF_DISCOUNT'],
    detailDescription: '감성 카페에서 오픈 시간대 스탭을 모집합니다.',
    workContentImg: null,
    applicationDeadline: '2026-02-10',
    applicationMethod: 'PLATFORM',
    contactName: '최사장',
    contactPhone: '010-7777-8888',
    contactEmail: null,
    isPremium: false,
    premiumStartAt: null,
    premiumEndAt: null,
    matchedVisas: MOCK_VISA_MATCHING_RESPONSE.eligible,
    allowedVisas: 'F-5,F-6,F-2,H-1',
    viewCount: 210,
    scrapCount: 45,
    applyCount: 18,
    companyName: '카페 라떼',
    companyLogo: null,
    createdAt: '2026-01-20T09:00:00Z',
    updatedAt: '2026-02-10T09:00:00Z',
    expiresAt: '2026-02-03T09:00:00Z',
  },
  {
    jobId: '10005',
    corporateId: '67890',
    boardType: 'PART_TIME',
    tierType: 'STANDARD',
    title: '논현동 주방보조 구합니다',
    status: 'DRAFT',
    jobCategoryCode: 'REST_KITCHEN',
    jobCategoryName: '주방보조',
    ksicCode: 'I',
    jobDescription: '설거지 및 간단한 식재료 준비',
    recruitCount: 1,
    hourlyWage: 10500,
    weeklyHours: 20,
    schedule: [
      { dayOfWeek: 'SAT', startTime: '10:00', endTime: '20:00' },
      { dayOfWeek: 'SUN', startTime: '10:00', endTime: '20:00' },
    ],
    isWeekendOnly: true,
    workPeriod: { startDate: '2026-04-01', endDate: null },
    address: { sido: '서울특별시', sigungu: '강남구', detail: '논현동 55-3 1층', lat: 37.5112, lng: 127.0297 },
    displayAddress: '서울 강남구 논현동',
    koreanLevel: 'NONE',
    experienceLevel: 'NONE',
    preferredQualifications: null,
    benefits: ['MEAL'],
    detailDescription: '논현동 한식당 주방보조를 구합니다.',
    workContentImg: null,
    applicationDeadline: null,
    applicationMethod: 'PLATFORM',
    contactName: '김채용',
    contactPhone: '010-1234-5678',
    contactEmail: null,
    isPremium: false,
    premiumStartAt: null,
    premiumEndAt: null,
    matchedVisas: [],
    allowedVisas: '',
    viewCount: 0,
    scrapCount: 0,
    applyCount: 0,
    companyName: '카페 라떼',
    companyLogo: null,
    createdAt: '2026-02-18T11:00:00Z',
    updatedAt: '2026-02-18T11:00:00Z',
    expiresAt: null,
  },
];

// ─── 구직자 검색 결과 목업 / Worker search results mock ───

export const MOCK_SEARCH_RESULTS: AlbaJobSearchItem[] = [
  {
    ...MOCK_COMPANY_JOBS[0],
    visaMatch: { status: 'eligible', conditions: [] },
    distanceFromSchool: '25분',
  },
  {
    ...MOCK_COMPANY_JOBS[1],
    jobId: '20002',
    visaMatch: {
      status: 'conditional',
      conditions: ['TOPIK 3급 이상 필요', '체류자격외활동허가 필요'],
    },
    distanceFromSchool: '40분',
  },
  {
    jobId: '20003',
    corporateId: '11111',
    boardType: 'PART_TIME',
    tierType: 'STANDARD',
    title: '신촌 마트 주말 판매 알바',
    status: 'ACTIVE',
    jobCategoryCode: 'MART_SALES',
    jobCategoryName: '마트 판매',
    ksicCode: 'G',
    jobDescription: '주말 마트 판매 및 정리',
    recruitCount: 3,
    hourlyWage: 10500,
    weeklyHours: 16,
    schedule: [
      { dayOfWeek: 'SAT', startTime: '10:00', endTime: '18:00' },
      { dayOfWeek: 'SUN', startTime: '10:00', endTime: '18:00' },
    ],
    isWeekendOnly: true,
    workPeriod: { startDate: '2026-03-01', endDate: null },
    address: { sido: '서울특별시', sigungu: '서대문구', detail: '신촌동 112-3', lat: 37.5557, lng: 126.9370 },
    displayAddress: '서울 서대문구 신촌동',
    koreanLevel: 'BASIC',
    experienceLevel: 'NONE',
    preferredQualifications: null,
    benefits: ['MEAL', 'STAFF_DISCOUNT'],
    detailDescription: '신촌 대형마트에서 주말 알바를 모집합니다.',
    workContentImg: null,
    applicationDeadline: null,
    applicationMethod: 'PLATFORM',
    contactName: '정매니저',
    contactPhone: '010-2222-3333',
    contactEmail: null,
    isPremium: false,
    premiumStartAt: null,
    premiumEndAt: null,
    matchedVisas: MOCK_VISA_MATCHING_RESPONSE.eligible,
    allowedVisas: 'F-5,F-6,F-2,H-1,D-2',
    viewCount: 75,
    scrapCount: 19,
    applyCount: 6,
    companyName: '신촌마트',
    companyLogo: null,
    createdAt: '2026-02-16T09:00:00Z',
    updatedAt: '2026-02-16T09:00:00Z',
    expiresAt: '2026-03-02T09:00:00Z',
    visaMatch: { status: 'eligible', conditions: [] },
    distanceFromSchool: '15분',
  },
  {
    jobId: '20004',
    corporateId: '22222',
    boardType: 'PART_TIME',
    tierType: 'PREMIUM',
    title: '건대 치킨집 배달/홀서빙',
    status: 'ACTIVE',
    jobCategoryCode: 'REST_SERVING',
    jobCategoryName: '음식점 서빙',
    ksicCode: 'I',
    jobDescription: '치킨집 홀서빙 및 배달 보조',
    recruitCount: 2,
    hourlyWage: 13000,
    weeklyHours: 24,
    schedule: [
      { dayOfWeek: 'FRI', startTime: '17:00', endTime: '01:00' },
      { dayOfWeek: 'SAT', startTime: '17:00', endTime: '01:00' },
      { dayOfWeek: 'SUN', startTime: '17:00', endTime: '01:00' },
    ],
    isWeekendOnly: false,
    workPeriod: { startDate: '2026-02-20', endDate: '2026-08-31' },
    address: { sido: '서울특별시', sigungu: '광진구', detail: '화양동 7-2', lat: 37.5413, lng: 127.0701 },
    displayAddress: '서울 광진구 화양동',
    koreanLevel: 'DAILY',
    experienceLevel: 'NONE',
    preferredQualifications: '배달 경험 우대',
    benefits: ['MEAL', 'TRANSPORT', 'BONUS'],
    detailDescription: '건대 인기 치킨 프랜차이즈에서 알바를 모집합니다.',
    workContentImg: null,
    applicationDeadline: '2026-03-01',
    applicationMethod: 'PLATFORM',
    contactName: '한사장',
    contactPhone: '010-4444-5555',
    contactEmail: null,
    isPremium: true,
    premiumStartAt: '2026-02-17T00:00:00Z',
    premiumEndAt: '2026-03-03T00:00:00Z',
    matchedVisas: [...MOCK_VISA_MATCHING_RESPONSE.eligible, ...MOCK_VISA_MATCHING_RESPONSE.conditional],
    allowedVisas: 'F-5,F-6,F-2,H-1,D-2,H-2,F-4',
    viewCount: 203,
    scrapCount: 56,
    applyCount: 15,
    companyName: '건대치킨',
    companyLogo: null,
    createdAt: '2026-02-14T09:00:00Z',
    updatedAt: '2026-02-17T10:00:00Z',
    expiresAt: '2026-02-28T09:00:00Z',
    visaMatch: {
      status: 'conditional',
      conditions: ['주 24시간 → TOPIK 3급 이상 필요'],
    },
    distanceFromSchool: '30분',
  },
  {
    jobId: '20005',
    corporateId: '33333',
    boardType: 'PART_TIME',
    tierType: 'STANDARD',
    title: '합정 사무보조 주3일 알바',
    status: 'ACTIVE',
    jobCategoryCode: 'OFFICE_ASSIST',
    jobCategoryName: '사무보조/번역',
    ksicCode: 'M',
    jobDescription: '데이터 입력 및 번역 보조',
    recruitCount: 1,
    hourlyWage: 14000,
    weeklyHours: 18,
    schedule: [
      { dayOfWeek: 'MON', startTime: '10:00', endTime: '16:00' },
      { dayOfWeek: 'WED', startTime: '10:00', endTime: '16:00' },
      { dayOfWeek: 'FRI', startTime: '10:00', endTime: '16:00' },
    ],
    isWeekendOnly: false,
    workPeriod: { startDate: '2026-03-01', endDate: '2026-08-31' },
    address: { sido: '서울특별시', sigungu: '마포구', detail: '합정동 22-1 3층', lat: 37.5497, lng: 126.9136 },
    displayAddress: '서울 마포구 합정동',
    koreanLevel: 'BUSINESS',
    experienceLevel: 'NONE',
    preferredQualifications: '영어/일본어 가능자 우대',
    benefits: ['TRANSPORT', 'FLEXIBLE_HOURS'],
    detailDescription: '스타트업 사무실에서 데이터 입력 및 번역 보조 알바를 모집합니다.',
    workContentImg: null,
    applicationDeadline: '2026-02-28',
    applicationMethod: 'EMAIL',
    contactName: '오팀장',
    contactPhone: '010-6666-7777',
    contactEmail: 'hire@startup.kr',
    isPremium: false,
    premiumStartAt: null,
    premiumEndAt: null,
    matchedVisas: MOCK_VISA_MATCHING_RESPONSE.eligible,
    allowedVisas: 'F-5,F-6,F-2,H-1,D-2',
    viewCount: 95,
    scrapCount: 30,
    applyCount: 9,
    companyName: '스타트업코리아',
    companyLogo: null,
    createdAt: '2026-02-12T09:00:00Z',
    updatedAt: '2026-02-12T09:00:00Z',
    expiresAt: '2026-02-26T09:00:00Z',
    visaMatch: { status: 'eligible', conditions: [] },
    distanceFromSchool: '20분',
  },
];

// ─── 프리미엄 공고 목업 / Premium jobs mock ───

export const MOCK_PREMIUM_JOBS: AlbaJobSearchItem[] = MOCK_SEARCH_RESULTS.filter(
  (job) => job.isPremium
);
